### ISSUE TITLE
In-World Pressure Tube Upgrading

### ISSUE THREAD

**Issue by TemperedFool** [TeamPneumatic/pnc-repressurized#1001]
### Describe the feature

I would like to be able to swap Pressure Tubes for Advanced Pressure Tubes, or upgrade them, in world. Could work by holding a wrench with the advanced tubes off-hand, or require a special upgrade item (like Mekanism allows you to upgrade tubes/cables in-world by whacking them with alloys).

### Reasons why it should be considered

I'd like to upgrade my backbone pressure line, and it's sad to lose the pressure built up in the tubes, and the inevitable leaks from compressors and devices in the process. Could be I'm just not quick enough doing it, but this would help a ton.

**Comment by TeamSpen210** [comment]
One way to help here would be to make a minor change to wrenching behaviour: when closing a tube end, if the adjacent block is a straight tube close that one too, to prevent leaking. It wouldn't apply when opening, so if you want the current result you can just open it. 

Then you could just wrench either end of a line, and go along and replace that isolated section. You'd then lose the pressure in the tubes, but that seems logical - it doesn't really make sense to be able to swap out an entire tube while somehow keeping the air in place.

**Comment by desht** [comment]
I'm not inclined to add in-place pressure tube upgrading, since it just doesn't make a lot of sense (and yeah I know reinforced chests can be upgraded in-place, but the concept of transferring solid items from one container to another makes a certain amount of sense; transferring air simply doesn't).

I'm not opposed to @TeamSpen210's suggestion though; it would save a little bit of air when isolating tube sections.

**Comment by desht** [comment]
Added @TeamSpen210's suggestion in 3.2.3 release: wrenching a straight tube section now also closes the neighbour if there would be a leak.
