### ISSUE TITLE
amadron levels 

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#1013]
### Describe the feature

Kinda hard to explain but i will try. so when i add amadron trades you have to set a level which is for the rarity of the trade. Would it be possible for the levels to be locked till a player gets a certain item or gets an achivment to unlock those level trades. eg getting a diamond would unlock Level 3 trades. Trades not avalible to the given player could be grayed out

### Reasons why it should be considered

provides modpack makers with a great deal of customization using amadron

### Additional details

![image](https://user-images.githubusercontent.com/42780877/170276855-913d671c-0839-4c91-969b-2a554eabb5eb.png)

**Comment by desht** [comment]
You can actually achieve this already on 1.16.5 with help from the Gamestages mod.  Some docs about this are here: https://github.com/TeamPneumatic/pnc-repressurized/wiki/Amadron-and-Datapacks#player-filtering

Not available on 1.18.2 yet, since Gamestages hasn't been ported, but I'll add support back if & when it does get ported.

Using this, you can make offers available dependent on whether the player has a specific stage granted to them or not.  Does that cover your needs?

**Comment by benbenlaw** [comment]
i think that would work on a single player world, but not sure how this would work with multiple players all having different stages

**Comment by desht** [comment]
Um, you said: "Trades not avalible to the given player could be grayed out".  Of course multiple players will have different stages, that's kind of the whole point.  This works based on what stage the player using the tablet currently has.

**Comment by benbenlaw** [comment]
ah ok so that could be a way of doing it then, looks like gamestages is out for 1.18.2

**Comment by desht** [comment]
So it is!  Next PNC:R for 1.18.2 will support it

**Comment by benbenlaw** [comment]
nice thanks for the help :)

**Comment by desht** [comment]
Gonna close this now, I think your needs are covered here?
