### ISSUE TITLE
Drone with "Drone Condition: Upgrades" widget crashes the server

### ISSUE THREAD

**Issue by Malgnor** [TeamPneumatic/pnc-repressurized#1019]
### Describe the bug

Using a drone with a Drone Condition: Upgrades in its program causes a server crash. After this the server will crash on startup and setting "stop_drone_ai" to "true" doesn't stop it from crashing.

### How to reproduce the bug

Add a Drone Condition: Upgrades widget to a drone program, upload program to drone then deploy drone, this will cause a crash.

This [drone progam](https://gist.github.com/Malgnor/e98a3ffc5675dd04f16c8acac2644163) should be enough to trigger the crash.

### Expected behavior

Drone program executing without crashing the server.

### Additional details

Modpack: [All the Mods 7-0.4.3](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3802141)
Mod version: pneumaticcraft-repressurized-1.18.2-3.2.3-84
Drone program I was trying to use when the crash happened the first time: https://gist.github.com/Malgnor/02ec02385a7ff43555090e70fef5b904

### Which Minecraft version are you using?

1.18

### Crash log

https://gist.github.com/Malgnor/dc35b95381ffd4d5fded13100ed7f540

**Comment by desht** [comment]
This will be fixed in the next release, which should be today.

However, your program is also incorrect, and shouldn't be exportable (it only is because of a separate bug which is also fixed in the upcoming release).  You have two conditions in your program with no text widgets on either the true or false branches, making those conditions useless - you'll see both conditions highlighted in red in the programmer GUI.

**Comment by Malgnor** [comment]
Ok, thanks!

About the conditions in my program, I'm using them to measure and the book states that no branching is required when measuring.

**Comment by desht** [comment]
Ah, good point.  Yes, that's valid, then.

**Comment by desht** [comment]
Fixed in 3.2.4 release
