### ISSUE TITLE
A drone that cannot get to a charging station still keeps it claimed

### ISSUE THREAD

**Issue by Quezler** [TeamPneumatic/pnc-repressurized#1022]
### Describe the bug

When a drone is out of pressure (e.g. pressure in the main system connected to a charging station ran out, or due to chunk loading issues) and can thus not fly or teleport to a charging station still keeps claiming it.

I ran into this issue on my previous & current enigmatica6 run, where my dozen of drones fail to charge since 4 drones that are somewhere and out of pressure keep claiming charge pads despite not being able to path to them.

The only solution seems to be to have at least as many charge pads as you have drones to ensure one will always be able to claim one, but this doesn't really feel like the direction the mod wants to take you in. (e.g. 1-4 pads with 10 speed upgrades feels more natural)

### How to reproduce the bug

Have more drones out of pressure than you have charge pads with a dispenser upgrades, then watch a drone that is nearly empty simply continue with its tasks and ignore its pressure level until it falls out of the sky.

### Expected behavior

For drones that cannot path/move/teleport towards a chargepad for whatever reason to relinquish their claim so that other drones may give charging themselves a try. 

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Can you try build 327 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16 and see if that helps?  Two very simple changes:
* Ensure charging station is actually chunkloaded (it should be in most cases, but it's not guaranteed)
* Don't place a claim if completely out of air, since that will lock every other drone out
With those two changes in place, I had a queue of about 10 drones and one charging station, and they all got their turn.

I do have a concern about drones not being able to path to the charging station - they should always be able to teleport, even if very low on air. Air is actually taken after the drone actually teleports, not before, so the drone should be able to arrive on the charging station with no air left.  If you have a scenario where a drone can't travel *or* teleport, I'd like to know about it.

**Comment by Quezler** [comment]
Whoops, i didn't notice this got a response yet 😅 

I'll try to give it a go tomorrow evening, but the fix to the claim issue looks pretty solid 👍

**Comment by Quezler** [comment]
i regret to inform you that unlike my previous playthough i am not in the position to test dozens (or even one) custom build(s), and that i won't be able to verify that drones no longer call dibs on where they can't manage to go, my apologies 🤔

**Comment by desht** [comment]
OK, we'll just need to hope those fixes resolve the problem then :)  Closing this, feel free to comment on it if you spot the problem in future...

**Comment by Quezler** [comment]
will do ^-^
