### ISSUE TITLE
Omnidirectional hopper causes render lag

### ISSUE THREAD

**Issue by jollycar** [TeamPneumatic/pnc-repressurized#1051]
### Describe the bug

When looking at a single Omnidirectional hopper, connected to a chest, there is a significant render lag (FPS reduced by 20%)

### How to reproduce the bug

place Omnidirectional hopper in the world

### Expected behavior

Fps should not drop by 20%

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.3.0-99

**Comment by desht** [comment]
I see no render lag at all when I look at an omnihopper.  FPS doesn't change whether I'm looking at a hopper or not.

Going to need much more information about your environment to determine what's causing this (probably not PNC itself since omnihoppers don't do any fancy clientside rendering or block shape calculations).

**Comment by jollycar** [comment]
I am playing the pack Plexiglass Mountain from FTB, latest version as of today, I moved myself out to a remote chunk and made this video: https://gifyu.com/image/SNbEd

What more info do you need a.t.m.? I'm happy to provide.

**Comment by desht** [comment]
You have Optifine in your pack.  Please test without OF (and any other "performance" mods) and let me know what results you get.

**Comment by desht** [comment]
Closed due to lack of response.
