### ISSUE TITLE
Stack overflow error.

### ISSUE THREAD

**Issue by DrSigma4164** [TeamPneumatic/pnc-repressurized#1052]
### Describe the bug

It's just that the stack overflows from time to time in the cold biome. The biome is called snowy tundra.

### How to reproduce the bug

I just went into the cold biome, walked around a bit, and I crashed

### Expected behavior

In order not to crash the server

### Additional details

If necessary, I can provide 3 crash logs.

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

2.15.11-334

### Crash log

https://pastebin.com/u9mLFHiU  https://pastebin.com/kpdLYbcm

**Comment by desht** [comment]
If you're in a position to test build 335 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/, it should hopefully fix that problem.  Otherwise, fix will be in the next release (2.15.12).

**Comment by DrSigma4164** [comment]
I installed this version. At the place where I had a crash, now it's like this:
![image](https://user-images.githubusercontent.com/93322905/179389379-3bb3808d-0ef0-418a-bdc4-dcd38e8d783e.png)

**Comment by desht** [comment]
Not sure what that is, but it's not PNC preventing chunk generation.

**Comment by DrSigma4164** [comment]
I don't really understand crash logs, but on lines 21 and 22, it says that something from the Ice and Fire mod is trying to spawn, maybe this is the problem?

**Comment by DrSigma4164** [comment]
I crashed again, here is the crash log: https://pastebin.com/Ga6HqKq9

**Comment by desht** [comment]
OK, this is on the Dread Spawner from Ice & Fire.  That tile entity for some reason creates its own `type` field which clashes with the vanilla `type` field that all tile entities have.  And when Forge goes to attach capabilities to tile entites, any dread spawners have a null tile entity type because Ice & Fire hasn't yet properly initialized its own private type field.  This is a bug in I&F as far I'm concerned, although I'll be kind and work around it in PNC.  But you should report this to them because it could easily break other mods too.

**Comment by desht** [comment]
build 336 should fix this

**Comment by DrSigma4164** [comment]
I am very grateful for such a step. Reported to the author of the I&F mod

**Comment by desht** [comment]
Worked around in 3.4.0 release (although the actual bug is in I&F)

**Comment by desht** [comment]
Fixed in 2.15.12 release
