### ISSUE TITLE
Right Click Puzzle Piece Micromissile Fails after initial right-click

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#1054]
### Describe the bug

When I deploy the drone, the first right click will fire the equipped micromissile, but subsequent right clicks fail to fire. The only way to get the drone to fire again is by breaking and redeploying. 

### How to reproduce the bug

Have the drone import Micromissile then right-click the air.
See video of behavior and simple sample program below.

### Expected behavior

The drone continues to fire micromissles on right-click command.
As discussed in discord - the internal cooldown of the micromissile itself may be the issue.

### Additional details

Pastebin --- https://pastebin.com/N7E0KxP5
Video --- https://youtu.be/P4tEPq1zeOY

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.3.1-110

### Crash log

N/A

**Comment by desht** [comment]
Yep, it was indeed cooldowns.  Drone's fake player cooldown manager currently doesn't get ticked; very easy fix, fortunately...

**Comment by desht** [comment]
This will be fixed in next release, but I'm actually going one further and adding first-class micromissile support to drones: if the drone is carrying a micromissile when Attack Entity executes, it will now point toward the target and launch a missile. Entity filters supported too (drone writes the puzzle piece's current filter to the micromissile).

**Comment by desht** [comment]
Fixed in 3.4.0 release
