### ISSUE TITLE
Aerial Interface enhancements (side selection, experience handling)

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#107]
Right now, the top & bottom slots of the interface connect to the player's armour inventory, and the sides connect to the main inventory.  It would be nice to add more flexibility to this; there is also the player's offhand inventory and perhaps also their Ender inventory (vanilla ender chests).

Proposal: add a GUI extension (via a side button) to allow the player to connect different faces of the Aerial Interface to different parts of the player's inventory.  Using absolute faces (D, U, N, S, W, E) is one option; if we wanted to use relative faces (D, U, Front, Back, Left, Right - like Thermal Expansion machines), the Aerial Interface would need to become a rotatable block.

**Comment by desht** [comment]
While on the Aerial Interface, the XP handling could use some attention:

* Add support for CoFH experience (Essence of Knowledge - internal fluid name: "experience", worth 1XP per 20mB, same as "xpjuice").
* Better document which experience types are accepted - right now, the fluid display name and internal name are shown in the exp sidebar.  Players don't really need to see the internal fluid name; it would be more useful to show the fluid display name and the providing mod's name.
* Consider allowing selection of accepted experience type in the interface's GUI; would this be more friendly than the current method of "teaching" the interface by pumping a bit of the desired fluid in?

**Comment by MineMaarten** [comment]
Sounds great! I think relative would be required, or else something like color coding the sides, to at least preventing F3-ing.

~~On the subject of sidedness, most machines could probably use a rework to match the more modern sidedness approach. A lot of machines are sided to specific slots while they could at least be smarter (items pumped in an Air Compressor go automatically to the right slot (upgrades/furnace) depending on their type), or what you propose, add a 'selection what you want' system.~~ I haven't looked at the sidedness of machines since 1.7.10. Good job sir ;). And after looking through the other machines, there aren't any currently that could also benefit from a custom sidedness GUI option, but it could be nice to make generic in any case to future proof if it's feasible :). 

I also agree with XP ideas, including the XP type selection. The situations where one uses the interface for both insertion ánd extraction of XP is probably rare. We could probably simply dropdownlist the options?

**Comment by MineMaarten** [comment]
One machine that also could benefit from configurable sidedness is the Programmable Controller, to configure which side maps to the drone internal inventory, and which side maps to the slot in the Programmable Controller that contains the drone program.

**Comment by desht** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/commit/c25ecce3d97b7ca6a10d4bfbeba9cb2c3da6d607

**Comment by desht** [comment]
Added in 0.8.0
