### ISSUE TITLE
Spawner agitator not working

### ISSUE THREAD

**Issue by Nevrai** [TeamPneumatic/pnc-repressurized#1071]
The spawner agitator doesn’t seem to do anything after being added to a spawner. The spawner does not spawn _any_ entities if the player is not nearby, despite the chunks being force-loaded with [FTB Chunks](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge). Two other people playing the same pack have told me that their spawner agitators don’t work as well.

The spawner is a vanilla spawner, but Apotheosis _is_ installed. No Apotheosis spawner upgrades had been applied, though, so it’s odd that the agitator doesn’t work, but I suppose despite the spawner being a vanilla one, Apotheosis still overrides it somehow. I believe, then, that this is the same issue as #1033 and #1063.

Is it possible that PneumaticCraft: Repressurized can be updated so that the agitator will work even with Apotheosis installed? I don’t understand why it can’t work with Apotheosis when its spawner upgrades aren’t being used.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version 0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **PneumaticCraft: Repressurized:** 3.4.0-124 (latest for 1.18.2)

**Comment by desht** [comment]
Let me guess, Apotheosis is also in the pack?

**Comment by Nevrai** [comment]
Yes, like I said, Apotheosis is installed. Hopefully this is something that PneumaticCraft: RP can fix? Getting a spawner agitator is a lot easier than getting a Nether star.

**Comment by desht** [comment]
I'm afraid it's not something that can be fixed in PNC:R, no.  Apotheosis actually replaces the block entity for spawners, and PNC:R uses a mixin into the vanilla spawner block entity to override the is-player-near logic.  I do not intend to try and mixin to another mod's code, and it's not PNC:R's place to do so.

**Comment by desht** [comment]
The following will be in the next release of PNC:R.  If Apotheosis is present:

* Crafting recipe for Spawner Agitator will be disabled
* Tooltip will be added to existing agitator items indicating the agitator is non-functional
* Agitators will not be placeable on mob spawners

**Comment by CantBeLucifer** [comment]
@desht I might add that as someone else has mentioned the feature that prevents mob despawning actually still works even with apotheosis. This is still a very useful feature as apotheosis does not have an equiavlent feature. Maybe just a tooltip would help, because completely disabling it would prevent this feature from being used.

**Comment by desht** [comment]
That's a fair point. I'll limit it to just warning via tooltip (and a page in the manual which is conditional on Apotheosis being installed).  And probably also warning the player via message when an Agitator is placed on a spawner.

**Comment by desht** [comment]
Fixed (docs & tooltip updated) in current 1.18/1.19 releases
