### ISSUE TITLE
Air conditioning upgrade crafting recipe broken

### ISSUE THREAD

**Issue by scarabx** [TeamPneumatic/pnc-repressurized#1096]
### Describe the bug

When I look the recipe for air conditioning upgrade up in jei, nothing happens.

### How to reproduce the bug

Look air conditioning upgrade up with jei.

### Expected behavior

No crafting recipe will show.

### Additional details

In older pneumaticcraft versions the upgrade only worked when tough as nails was installed. I have tough as nails installed. Is that the problem? Should I use survive mod instead?

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.1.2

**Comment by desht** [comment]
The Air Conditioning unit doesn't actually do anything (and hasn't since 1.12.2, when there was Tougher than Nails integration.  I might look at re-adding TAN at some point, but they changed their licence when they finally ported to 1.16+,  making it harder to work with the mod, so it's not a priority.
