### ISSUE TITLE
Add the Warden to the default list of blacklisted Vacuum Trap mobs

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#1101]
### Describe the feature

As it stands, the Warden is not currently blacklisted in the Vacuum Trap. It should be added to the list of default blacklisted mobs.

### Reasons why it should be considered

- It's a boss mob like the Wither and Ender Dragon.
- It has griefing potential, becuase it causes a blindness effect on nearby players and it's *very heavy* sonar attack can penetrate through fluids, walls  and shields.

**Comment by desht** [comment]
Yeah, probably.  Interestingly the game doesn't flag it as a boss in the same way that the Wither or Dragon are flagged (there's a `boolean canChangeDimensions()` entity method which returns false for boss mobs - Botania's Gaia Guardian also does this.

I'm inclined to hardcode the Warden as blacklisted in the same way other bosses are, rather than use the blacklist tag.

**Comment by desht** [comment]
Fixed in latest release
