### ISSUE TITLE
ATM8 Issue with PNC:R 

### ISSUE THREAD

**Issue by DrFiishy** [TeamPneumatic/pnc-repressurized#1104]
### Describe the bug

So after installing ATM8 and booting up the server every so often an error pops up with 

''[Server thread/WARN] [pneumaticcraft/]: Amadron: failed to find any trades for profession evilcraft:werewolf ?''

### How to reproduce the bug

Install ATM8 1.0.4 Server

### Expected behavior

For the error not to show up cause im honestly confused on how werewolf is a profession

### Additional details

Hopefully there is a way to maybe blacklist a certain profession or maybe even add it to Amadron

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.1.2-9

**Comment by desht** [comment]
The warning (not error) is completely harmless, so you can just ignore it. Evilcraft does in fact register a "werewolf" villager profession, but I guess it doesn't add any trades to it.  The Amadron system periodically scans all known villager professions, looking for trades at random to add to the live offers list, and just warns about the lack of werewolf trades, because it's strange having a villager profession which doesn't have any trades.

**Comment by pieterbrandsen** [comment]
@desht I noticed that it could take a lot of tick time and even lag my players out of the server.

https://spark.lucko.me/ePbW1nkOEp
![image](https://user-images.githubusercontent.com/45623682/232768986-2e97d471-4b29-43c8-8e55-5bd89ac93d3a.png)

As can seen in the image it took 49k ms for the ONE tick to handle this. Also seen one of 69k.
![image](https://user-images.githubusercontent.com/45623682/232769445-882c1cc0-90b6-47ee-8e7d-7fb6416f7bb8.png)

My fix for now would be to turn this trader off as we dont use it for our playthrough.

Any advice would be welcome. 

Atm8, I7-8700k, 32gb ram ddr4 (4-24gb assigned), playing on Seagate IronWolf 8TB

**Comment by desht** [comment]
Given that message is logged at most once every 20-30 minutes, if logging _a single line of warning text_ is lagging your server that badly, I would suggest your server has much more serious problems than a slightly chatty mod.

The culprit here is much more likely to be `net.minecrell.TerminalConsoleAppender`, the class that is _actually_ chewing up your CPU time.  I'd take a closer look at why that is lagging your server out.

**Comment by pieterbrandsen** [comment]
Okay I need to say your correct, its perfectly timed with the mod so I guessed it was yours but it looks like the server is the problem and not the profession. It could write all other warn messages perfectly fine so not sure why but I will look into it.

![image](https://user-images.githubusercontent.com/45623682/232805235-8b324548-93e7-4294-8c52-7a07424df366.png)
