### ISSUE TITLE
Fluid Tank rendering issue

### ISSUE THREAD

**Issue by fixthissitepls** [TeamPneumatic/pnc-repressurized#1121]
### Describe the bug

Fluid Tank seem to have a rendering issue where the transparent part is rendered with a black and white overlay when placed down. Adding or removing fluids wont change the texture at all. No Optifine.
I also included a Debug Crash log just in case.

![2023-01-11_15 35 27](https://user-images.githubusercontent.com/118289704/211835310-b174b8b7-5db4-48dd-8400-876922cf1f89.png)

[crash-2023-01-11_15.47.26-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/10393426/crash-2023-01-11_15.47.26-client.txt)

### How to reproduce the bug

Place down tank and look at it.

### Expected behavior

Texture should be transparent.

### Which Minecraft version are you using?

1.19.2

### Which version of PneumaticCraft: Repressurized are you using?

v1.19.2-4.2.0 (newest)

**Comment by desht** [comment]
Rubidium is causing this, although my tank models are fine (and work fine without Rubidium) - they are just JSON models, nothing special.  I would take this issue up with the Rubidium dev.

**Comment by desht** [comment]
Probably also worth mentioning that tanks render fine in 1.18.2 with Rubidium installed - the only change made to tank models in 1.19.2 is using the Forge-required change of putting `render_type: "cutout_mipped"` in the block model instead of the old way of setting the block render type in code.

So yeah, Rubidium issue.

**Comment by fixthissitepls** [comment]
Alright gonna put the issue to them thank you.
