### ISSUE TITLE
Global Var Remote Crash , ATM7 Modpack

### ISSUE THREAD

**Issue by superjaja05** [TeamPneumatic/pnc-repressurized#1126]
### Describe the bug

The game crashes after clicking a button on a remote that sets a global var

### How to reproduce the bug

Have a remote's button that sets a global var, click it
The one i use : https://pastebin.com/gzXehGZY

### Expected behavior

The game not crashing

### Additional details

The crash seems to be client-side since the server doesn't crash, and the modpack is ATM7 if that matters

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.4.3-8

### Crash log

https://pastebin.com/gpBceg9A

**Comment by desht** [comment]
The problem here is your variable in the label widget that shows the current value, where you've put `${tpOneSpeed}` - that should be `${#tpOneSpeed}` since `#tpOneSpeed` is a global variable.  Changing that will fix your crash.

However, PNC shouldn't just crash in this case.  Next release will assume you mean `${#tpOneSpeed}`, but will send you a warning reminder about the missing prefix when you open the Remote, if it has any variable references to non-global variables.

**Comment by superjaja05** [comment]
Oooh i see, i think i made my remote in older versions where i didn't need a prefix so it worked nicely.
Anyway thanks for helping me

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
