### ISSUE TITLE
Assembly Drill Brakes

### ISSUE THREAD

**Issue by Bitgedon** [TeamPneumatic/pnc-repressurized#1146]
### Describe the feature

I wouldn't say this is a feature but it's also not really a bug.

The drill on the assembly drill slows down at a constant rate regardless of how many speed upgrades it has. 
This means that each new speed upgrade added has diminishing returns since regardless of how fast the arms move. You'll still be waiting for the drill to decelerate. 

### Reasons why it should be considered

It's good for automation since ultimately it speeds up the assembly line but much more minorly, it removes that unsatisfying gap of time in where you just get to watch the system do nothing. I spend a lot of time watching the assembly line works because I'm an animation nut and nothing bugs me more than that 3-4 second gap of time where nothings happening.

### Additional details

I made no attempt to time how long it takes for the drill to decelerate, these observations are purely eyeballed. I could be completely wrong about this and speed upgrades could affect it and I would have no idea. In that case I'm sorry for wasting your time.

**Comment by desht** [comment]
Yeah, I know what you mean; the drill slowdown time can be bit incongruous once you have a lot of speed upgrades in the assembly system.  I'll take a look at maybe reducing that time based on upgrades.

**Comment by desht** [comment]
It's these lines here: https://github.com/TeamPneumatic/pnc-repressurized/blob/010901c4c6018cee5516d7bbaa7323c72a43a42c/src/main/java/me/desht/pneumaticcraft/common/block/entity/AssemblyDrillBlockEntity.java#L54-L56

Oddly, speed upgrades affect spin-up, but not spin-down.  It's always been this way (since back in the 1.7.10 days), I wonder if it was intentional or an oversight?

**Comment by desht** [comment]
Added in 4.3.4
