### ISSUE TITLE
Server Tick Loop When Changing Default Oil

### ISSUE THREAD

**Issue by EmosewaPixel** [TeamPneumatic/pnc-repressurized#115]
Minecraft Version 1.12.2
Forge Version 14.23.2.2611
Mod Version 0.4.0-136
Describe your problem, including steps to reproduce it
Whenever the default Oil changes, PneumatiCraft causes a server tick loop without having anything from it placed:
https://pastebin.com/SEr8JH6u
 I have gotten this on 2 occasions:
1. Having Imnersive Petroleum and PneumatiCtaft present where Immersive Petroleum's Oil was the default and then adding BuildCraft (which made it's Oil the default)
2. Yet again having those 2 mods present and adding GalactiCraft (making its Oil the default)

**Comment by desht** [comment]
Yeah, this is a well-known recurring issue.  PNC is sensitive to other mods adding oil fluids since it needs to  do worldgen with oil fluid blocks by default.  See https://github.com/TeamPneumatic/pnc-repressurized/issues/30 for a lot more discussion on this.  In short, though you can either:

* Try to get PNC to load _before_ all other oil-providing mods (see the above thread)
* Simply disable PNC's oil worldgen, and let PNC use the oil fluid from the other mod(s).  If you're developing a skyblock, that's probably what you want anyway.  See ``D:oilGenerationChance`` in ``pneumaticcraft.cfg``.

**Comment by desht** [comment]
Problem should be resolved in 0.4.1 release.
