### ISSUE TITLE
The game stops responding

### ISSUE THREAD

**Issue by Developer2704** [TeamPneumatic/pnc-repressurized#1151]
### Describe the bug

the bug causes the game to stop responding and the last thing in the debug log is 

 [modloading-worker-0/INFO] [pneumaticcraft/]: Thirdparty integration activated for [jei,patchouli,create]

### How to reproduce the bug

install these mods

Saturn
AbdElAziz333
saturn-mc1.19.2-0.0.1.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.19.2-8.1.0.24.jar

Serene Seasons Fix
Or_OS
sereneseasonfix-1.19.2-1.0.7.jar

Shutup Experimental Settings!
Corgi_Taco
shutupexperimentalsettings-1.0.5.jar

Structory
botanydev
Structory-1.19-v1.3.jar

Structory: Towers
botanydev
Structory_Towers_1.19_v1.0.1.jar

Structurize
H3lay
structurize-1.19.2-1.0.483-ALPHA.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-forge-1.19.2-0.5.0.jar

Valhelsia Furniture
ValhelsiaTeam
valhelsia_furniture-forge-1.19.2-1.0.2.jar

Wabi-Sabi Structures [FORGE]
shadow_of_wights
Wabi-Sabi-Structures-1.1.2-Forge.jar

WorldEdit
sk89q
worldedit-mod-7.2.12.jar

### Expected behavior

i expect the game to load

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.3

**Comment by desht** [comment]
I don't see this happening either in my dev instance or my test dedicated server.  And just because PNC was the last thing to log something doesn't mean it's reponsible for the lockup. PNC has no integration with any of the mods you listed so if your instance is hanging with those installed, I would suggest looking at those mods.
