### ISSUE TITLE
Compatibility with ad Astra 

### ISSUE THREAD

**Issue by Thunderrock424242** [TeamPneumatic/pnc-repressurized#1200]
### Describe the feature

Pressurized air basically when coming in and out of a airlock you have to pressure the air so nothing bad happens.

### Reasons why it should be considered

It would be very cool feature to have or you can make it a feature too for oceans and to pressure underwater areas

**Comment by desht** [comment]
How would this actually work?  I don't really understand the idea.

**Comment by HipHopHuman** [comment]
I know this issue is closed, but for future reference, this sort of compatibility is better handled by an addon mod, and there is an addon for Ad Astra called Ad Astra Giselle Addon which bridges some functionality between PNC and Ad Astra. Not sure if it helps airlocking, but that's the best place at the moment to look for this sort of interop.
