### ISSUE TITLE
[Suggestion] Have refinery multiblock take heat from higher refinery

### ISSUE THREAD

**Issue by Vyraal1** [TeamPneumatic/pnc-repressurized#121]
Right now it seems that only the bottom refinery takes heat and adds it to the total multiblock. Would it be possible to allow for other parts of the refinery to also take heat up as well?

**Comment by desht** [comment]
Yeah, this is a reasonable request. Should be in the next release.

**Comment by desht** [comment]
This is in build 150+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ if you'd like to do some testing ahead of the next official release.  In particular, making sure it works well when breaking/replacing parts of the multiblock.

**Comment by MineMaarten** [comment]
After discussing with @desht we came to the conclusion that:
1. The solution created above unfortunately does not what you would like.
2. We decided that how it currently works is how it should work, as this is how it works IRL as well. You heat the oil, which is at at the bottom of the refinery, so that's where the energy is used (to heat the oil).

It's therefore intentional that heating the top refinery block works, but is less efficient. One way to make this set-up work better though is by insulating the refinery blocks by placing down blocks around the refineries which do conduct heat (most blocks).
