### ISSUE TITLE
Server console spamming with ATM9 modpack

### ISSUE THREAD

**Issue by AP1028** [TeamPneumatic/pnc-repressurized#1216]
### Describe the bug

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/105597219/bb1f937e-05be-4333-90a3-351a8010e6ce)
The Amadron will search for all the trades in the mod pack. When using with evilcraft, pnc will returns a warning as `evilcraft:werewolf` does not have any profession.

### How to reproduce the bug

Install the ATM9 modpack, use pnc with evilcraft, or use pnc with any kind of mod that has a profession without a trade.

### Expected behavior

No spamming in the console.

### Additional details

Despite being harmless, the spamming is very annoying when I am trying to know what is going on in the server. I hope there will be a config for disabling warnings in the console.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.4

**Comment by desht** [comment]
Actually what might be better is to have the mod remember what it has warned about, so that it only warns the first time (per  server start) that it sees a villager type with no trades.  So you'll see one warning only for `evilcraft:werewolf`.

Update: actually, I'm just gonna suppress this warning entirely. It's not useful to server admins, and there are situations where it can validly happen (I'm guessing in this case Evilcraft adds only higher-level trades for the werewolf).

**Comment by desht** [comment]
4efe63cb28b0a549bf6e4e2cdd86f76fc355f385

**Comment by desht** [comment]
Fixed in 6.0.7 release (messages no longer logged)
