### ISSUE TITLE
Upgrade Expander

### ISSUE THREAD

**Issue by AP1028** [TeamPneumatic/pnc-repressurized#1223]
### Describe the feature

Upgrade Expander - a kind of upgrade that adds one additional upgrade slot for every upgrade expander installed.

### Reasons why it should be considered

All the pneumatic armor pieces have only 9 upgrade slots. Currently, the pneumatic helmet cannot fit in all the upgrades. With [Ad Astra Giselle Addon](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon), this problem becomes even worse. I must trade something useful for space space-breathing upgrade if I want to go to ad astra dimensions. 
With more upgrades being added to the mod, more items and (maybe) machines will be running out of upgrade slots. The upgrade expander would be very useful.

**Comment by HipHopHuman** [comment]
Note that I don't speak for Desht or PNC, but I am certain that this "problem" is intentional / working as intended. You're not supposed to be able to use all the upgrades at the same time. You can however use an Aerial Interface to automatically remove and replace the armor you're wearing from a remote location, and you can bind that to a button on the Remote, so you can dynamically switch between upgrades without having to carry a bunch of armor pieces on you.

**Comment by desht** [comment]
As a lower tech solution, you can carry a Charging Station with you and use that to switch out upgrades in the field.  There's a little button in the Charging Station GUI which disconnects the air line (just under the pressure gauge), effectively turning the block into a pure "upgrade station". The setting is remembered when the block is picked up and placed down again.

Increasing the number of item upgrade slots isn't a planned feature, sorry.
