### ISSUE TITLE
Liquid Duplication Glitch

### ISSUE THREAD

**Issue by peetzaecksdee** [TeamPneumatic/pnc-repressurized#1233]
### Describe the bug

I was playing in UniversIO modpack, when I wanted to auto craft the speed recipe, it decided to put the tank back into the inventory. So as a lazy person, I put the tank inside the crafting slot (with an empty tank in the inventory). After that, I realize, I just duped a liquid from a tank, also stacking the tank.

### How to reproduce the bug

1. Have an empty tank inside the inventory and place the filled tank inside the crafting slot
![Screenshot 2023-10-01 151103](https://github.com/TeamPneumatic/pnc-repressurized/assets/93785959/64c7555e-6c9e-4af4-93a4-55d5dde420e1)
2. Select a recipe in which the fluid tank is present in
![Screenshot 2023-10-01 151115](https://github.com/TeamPneumatic/pnc-repressurized/assets/93785959/f3b3f67a-e223-495f-88f0-227c115fbe63)
3. Auto craft the recipe and Voila, double the liquid
![Screenshot 2023-10-01 151127](https://github.com/TeamPneumatic/pnc-repressurized/assets/93785959/6eb1d2ac-4a6f-4b77-9472-0efd85e343db)

### Expected behavior

I was expecting the tank to be put back inside the inventory (I mean, why wouldn't it be that way)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.6-27

**Comment by desht** [comment]
Can't reproduce this, not with a vanilla Crafting Table anyway.  The tank always stays in the Crafting Table after a crafting operation, until it's removed by the player.  And there's never any combining with empty tanks in the inventory.

Looks to me like the problem is with the Philosopher's Stone.

**Comment by peetzaecksdee** [comment]
I tried it with the vanilla crafting table too, it produces the exact same result as done in the Philosopher's Stone. It could just be a problem with the modpack I'm playing with.

EDIT: I did try it with no other mods other than REI and this mod, still the exact same result.

**Comment by desht** [comment]
Definitely something up with your pack then. The fluid tank is specifically set to remain in the crafting table when used and not emptied:  https://github.com/TeamPneumatic/pnc-repressurized/blob/1.20.1/src/main/java/me/desht/pneumaticcraft/common/block/FluidTankBlock.java#L204-L219 (that's 1.20 I know, but it hasn't changed since 1.19)

So if something's moving the tank back into the inventory before it's empty, that something is bugged.

**Comment by peetzaecksdee** [comment]
I supposed the problem has something to do with the REI mod, I was using the version 9.1.632. Much like the problem with https://github.com/shedaniel/RoughlyEnoughItems/issues/1435 as I've found when checking the Issues. So the problem could be from the REI mod, not from this mod.

EDIT: The issue does not persist when using the newer version of the REI mod.

Thank you for checking on this issue.
