### ISSUE TITLE
Drones can't teleport to unloaded chunks (even if they are carrying a player)

### ISSUE THREAD

**Issue by Henrique143** [TeamPneumatic/pnc-repressurized#1240]
### Describe the bug

Programed drones fail to use the "Teleport Widget" to teleport to an area located in unloaded chunks, even if they are carrying a player (player mounted on the drone).

### How to reproduce the bug

Program a drone to use the "Teleport" widget to teleport to an area located in unloaded chunks, spawn the drone, the teleport fails.

Program a drone to pickup a player using the "Import Entity" widget, then to use the "Teleport" widget to teleport to an area located in unloaded chunks, spawn the drone, the teleport fails.

### Expected behavior

The drone should complete the teleport, especially if they are carrying a player (who would load the chunks afterwards).

### Additional details

It happened while playing in a "All the Mods 9" server (0.2.5)

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.9+mc1.20.1

**Comment by desht** [comment]
This is intentional, since teleporting into ungenerated chunks can cause server performance & stability problems. See #1129 for more discussion.

If you really want to be able to do this, see the `allow_navigate_to_unloaded_chunks` setting in the mod config. Setting that to true will allow drones to teleport anywhere - but as the setting comment says: "Setting this true may lead to server performance and stability issues - beware"

**Comment by Henrique143** [comment]
Thanks for the response!
It think it would be nice if the drones were to be able to teleport to "unloaded but already generated chunks", but I am not sure if it is even possible to make this distinction.

**Comment by desht** [comment]
I did some research back when the original problem was reported, and sadly no - it isn't possible to distinguish "not loaded" from "not generated yet".
