### ISSUE TITLE
Selling items with nbt

### ISSUE THREAD

**Issue by SatyrRex** [TeamPneumatic/pnc-repressurized#125]
I run a server, and I would like to be able to use nbt data when adding items to the periodic offers of the Amadron Tablet. For instance, from Robot Parts (cyberware), the salvaged parts have nbt data of .withTag({cyberwareQuality: "cyberware.quality.scavenged"}) I understand the damage is for the metadata, but I'm not that familiar with JSON to know what to add for nbt data.

**Comment by MineMaarten** [comment]
Hmm after looking into it, it turns out that Amadron currently does not support NBT items :O, at least as the json is concerned. We will look into adding support for it. 

After that, for the required notation, you could simply add a trade in-game with the item you want, and it will be added to the AmadronOffersStatic.json, after which you can simply copy over the definition.

**Comment by desht** [comment]
As of build 242, the Amadron got a bit of a revamp.  Custom periodic trades can now be added via the tablet GUI (second button on the new "Custom Trades" side tab), assuming the player is an admin - i.e. has the Forge permission node ``pneumaticcraft.amadron.addPeriodicTrade``, which by default is true for ops, and false for anyone else.

In addition, items saved to ``AmadronOffersPeriodic.cfg`` now include any NBT tags, so adding NBT-holding items should work (I've tested it with vanilla items - potions & enchanted books).  It's important to note that the Amadron system will always do an exact match on both item metadata and NBT.

These changes will be available in the upcoming 0.7.4 release.

**Comment by desht** [comment]
0.7.4 released
