### ISSUE TITLE
[1.19.2] Server crash trying to make netherrite drill bit

### ISSUE THREAD

**Issue by Saereth** [TeamPneumatic/pnc-repressurized#1259]
### Describe the bug

Several people have reported a server crash when trying to make the netherrite drill bit without inserting the laser program. This occurs in the FTB Genesis modpack, the recipe is unchanged from vanilla pnc.

### How to reproduce the bug

Craft a netherrite drill bit in in the laser assembly without the laser program inserted.

### Expected behavior

Not to do anything since its missing the proper program

### Additional details

also happened to Xobias on stream but he got it working after inserting the program

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.10-42

### Crash log

https://github.com/FTBTeam/FTB-Modpack-Issues/files/13432517/crash-2023-11-21_20.23.09-server.txt

**Comment by tabernacle8** [comment]
In your report you said "without the laser program" but JEI calls for the drill program. I had this with the drill program and it still crashed. Is JEI wrong?
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/19417482/06c6058b-e57b-43bb-a7be-6bde8205a1e8)

**Comment by Saereth** [comment]
Sorry yeah, Xobias had the laser program in there insteasd of the drill program, the drill program is what it should have

**Comment by desht** [comment]
Normally the controller scans for the machines required by the program and refuses to run if the necessary machine isn't part of the multiblock structure, but it looks like something's causing the system to think it's present when it's not.

I'll add some extra validation to this to prevent the crash (though can't 100% guarantee the problem is fully fixed since I can't reproduce it myself). My theory is something is causing the drill to disappear without causing a block update (which notifies the assembly controller to rescan for blocks).

**Comment by tabernacle8** [comment]
You are right, I was unable to replicate on a private world (FTB Genesis, 1.3.0). However on a server, I was able to achieve the same crash first try (FTB Genesis, 1.3.0).

Here's the video and log that might help:
https://youtu.be/er6H9808cv4

[crash-2023-11-24_08.19.14-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13459498/crash-2023-11-24_08.19.14-server.txt)

**Comment by desht** [comment]
PNC:R 4.3.11 is out on CF now and should be in the next version of Genesis.

However if you're in a position to test, feel free to drop it into your existing Genesis server; it should fix the problem.
