### ISSUE TITLE
Enhancement: Disable Jackhammer HUD

### ISSUE THREAD

**Issue by ratkinsonuk** [TeamPneumatic/pnc-repressurized#1262]
### Describe the feature

Please can you add a client config option to allow the Jackhammer HUD to be disabled, or move it somewhere less visible. It's really distracting and spoils a great tool.

Thanks, Rob.

### Reasons why it should be considered

Too much information on screen, which to be honest, isn't actually required. You tend to know what mode it's in, and it's not difficult to find out without it being there permanently.

### Additional details

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/25905667/436a5241-27ac-4ef2-9f45-8209faab945f)

**Comment by ratkinsonuk** [comment]
Just thinking, maybe this is actually an unintended bug as I've just noticed the 1x1 mod HUD disappears after a few seconds. Should all of the modes be doing that?

The version in 1.19.2-4.3.10-42 as part of the FTB Genesis modpack.

**Comment by desht** [comment]
No, it's intentional that the 1x1 mode disappears after a while and the others don't.  While the multi-mode indicators are a little distracting, they're there to remind you you're in a multiblock mode.  Because as annoying as they might be, it's less annoying than accidentally veinmining your base.

I disagree with "You tend to know what mode it's in" personally - it's very easy to leave the miner in a 3x3-full mode and forget - but I'll add a clientside config to disable it. Just don't complain to me about huge holes in your base :laughing:

**Comment by desht** [comment]
Added in 4.3.11.  Will be in next release for 1.20.1 as well when that happens.
