### ISSUE TITLE
Pressure Chamber and Memory Essence recipe viewers are missing with EMI.

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1344]
### Describe the bug

With only PNC and JEI installed, I can see all recipe tabs.
As soon as I add EMI to the mix, I lose the Memory Essence and Pressure Chamber tabs. 

These were working with pnc 8.0.3

### How to reproduce the bug

1. Install all three mods
2. Look for recipes for Compressed Iron
3. Note that only explosion crafting shows. Pressure Chamber recipes still work.

### Expected behavior

Recipes viewers should be visible

### Which Minecraft version are you using?

1.21.1

### Which version of PneumaticCraft: Repressurized are you using?

8.1.1

**Comment by MuteTiefling** [comment]
https://gist.github.com/MuteTiefling/96b6978ab0a9e3cdaa0e96f6853d7a82

**Comment by milkev** [comment]
EMI Pressure Chamber and Memory Essence categories are also broken on 8.1.0. All the other recipe categories seem to be working fine. Frustratingly (and as seen in the latest.log tiefling provided) there is no error log related to it. its just gone.

Can confirm going back to 8.0.3 brings the categories back.

**Comment by desht** [comment]
I suspect it's related to PNC 8.1.x moving to (requiring) a more recent version of JEI, where the EMI integration isn't working as well as it should.  I haven't made any changes to JEI functionality, other than replacing a few deprecated JEI API calls with their new equivalents.

This does very much appear to be a JEI/EMI integration issue, and something that needs to be fixed between those two mods. I really don't wish to be forced into a older version of JEI due to this, and I don't think this is something I can do anything about on the PNC side.

**Comment by desht** [comment]
Also, while memory essence recipes do appear to be missing, Pressure Chamber recipes are working fine here. Tested with EMI 1.1.12+1.21 and JEI 19.14.0.138.

**Comment by MuteTiefling** [comment]
Alright, thanks for looking into it. I've reported to EMI.

**Comment by desht** [comment]
I've had a change of heart, and I'm gonna roll back to the older JEI API for now (even though it's marked deprecated for removal). Hopefully EMI will update the JEMI component to use the newer JEI API soon, but best to keep stuff working for now, or we'll both be getting issues :stuck_out_tongue: 

8.1.2 release (today with luck) will sort this out.

**Comment by MuteTiefling** [comment]
Much appreciated, thanks!

**Comment by desht** [comment]
Worked around in 8.1.2
