### ISSUE TITLE
Elevator callers bugged after you have over 12 floors

### ISSUE THREAD

**Issue by williamforber** [TeamPneumatic/pnc-repressurized#136]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

**Comment by desht** [comment]
Yeah, I suspect 12 will be the limit, given that's the max number of buttons the elevator caller can display (2 columns of 6).

We'll consider some options to either make more buttons available somehow (multiple pages? smaller buttons?) or alternatively make it clearer (and handle more gracefully) that more than 12 buttons won't work.

**Comment by williamforber** [comment]
my building has 33 floors

**Comment by desht** [comment]
After some discussion, we will most likely to go with the paged option: when there are more than 12 buttons, only 12 will be displayed at a time, and buttons will be shown to move to the next or previous page.

**Comment by MineMaarten** [comment]
Hmm it turns out we actually already support many floors:
![2018-04-14_14 51 07](https://user-images.githubusercontent.com/5345405/38768398-73e664ce-3ff3-11e8-9e9f-f3406b2eae59.png)
However indeed this is buggy, it feels like the mouse x position is inverted, so pressing on the '8' button actually triggers the '57' button. I'll look into this right now.

**Comment by alexiokay** [comment]
- i still have this issue. i click on right side floor on caller and it turns on the floor on left side. my version:  pneumaticcraft-repressurized-8.2.12+mc1.21.1.jar
