### ISSUE TITLE
Omnidirection hopper entity tracking does not work

### ISSUE THREAD

**Issue by Popchip9** [TeamPneumatic/pnc-repressurized#1360]
### Describe the bug

Attempted to use omnidirection hopper on a server in craftoria 1.5.0 i could not get it to input or output when facing into or away from a witch horizontally, i then attempted horizontally and vertically on myself to check if it was just not working with a witch but it couldnt interact with me at all either

### How to reproduce the bug

Face entity with omnidirectional hopper using entity tracking upgrade and try to insert/remove items 

### Expected behavior

It should be inserting/removing items but it didnt

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.1.3

**Comment by desht** [comment]
Yeah, it doesn't work right now, because the way entity capabilities work in Neoforge 1.21 is quite different from Forge in 1.20. The entity automation capability (which allows sided access to the player) isn't added to players at all any more. The plain entity capability is added, but that doesn't allow sided access, so there's no way to differentiate between the player's main inventory and armor slots.

Not quite sure how to work around this right now, might need to have a chat with the Neoforge devs and figure out the best solution.

**Comment by Popchip9** [comment]
Ok thanks good to know, annoying that this limits my automation though hopefully you can fix it soon.

**Comment by desht** [comment]
Think I might have an idea, actually.

**Comment by desht** [comment]
Fixed in 8.2.0 release
