### ISSUE TITLE
Pneumatic Helmet : Sound glitch with Charging Station

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#158]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it

Opening the Charging Station GUI with any Pneumatic Helmet Module (tested with Block Tracker, Entity Tracker, Item Search Upgrade, Coordinate Tracker Upgrade) will loop a PNC sound while you stay in the interface.

**Comment by desht** [comment]
It's happening because of Minecraft item-equip sounds.  They're played when an item is placed into a slot - the client plays the sound when it gets a "set slot" packet.

Problem is, when the charging station GUI is open, the worn helmet's pressure is slowly changing (air draining).  So the item stack in the equipped slot is changing, which means the "set slot" packet is constantly being sent to the client... and you get an equipping sound effect looped.

Looking for a workaround/fix now.

**Comment by desht** [comment]
Looking through the Minecraft code, I can't see a way of suppressing this, other than to give the Pneumatic Helmet a material with an empty item-equip sound effect.  Whenever the helmet's NBT changes (i.e. when its stored air drains), the armor wrapper updates the stack in the armor slot in the charging station GUI, causing a "set slot" packet to be sent to the client, and that always causes the item-equip sound to be played.

**Comment by Sewef** [comment]
Maybe play the sound at the beginning of the helmet loading (this progress bar on the screen) instead of playing on equip ?

**Comment by desht** [comment]
With the way Minecraft & Forge are currently written, that's not possible.  However, I've found a better workaround (it occurred to me that the normal player inventory window displays armor items and doesn't have this issue, so I'm borrowing that code :)

**Comment by desht** [comment]
Fixed in 0.6.4 release
