### ISSUE TITLE
Some items from Factory Tech not showing up in the Item Filter

### ISSUE THREAD

**Issue by wrincewind** [TeamPneumatic/pnc-repressurized#185]
### Minecraft Version
1.12.2
### Forge Version
14.23.3.2676
### Mod Version
PNC: 1.12.2-0.5.1-163
Factory Tech: 1.3.5 (1.1.5)

### Describe your problem, including steps to reproduce it
in a Programmer, When populating an Item Filter using the 'Search Item' filter, the Wooden Mesh from factory Tech simply does not appear. I think it might be because all the Factory Tech machineparts are just called 'factorytech:machinepart' but i can't exactly tell. 
### Any other comments?
This is fairly easily remedied by using 'select from inventory' but if the item is hard to get, well, blah. D:

**Comment by desht** [comment]
Just took a look at the Factory Tech source, and I suspect it may be down to the fact that FT doesn't appear to be defining a creative tab for its machine part items - https://github.com/dalapo/FactoryTech/blob/master/src/main/java/dalapo/factech/item/ItemMachinePart.java#L33

Our GUI search code does need items to have a creative tab (it's not possible to get the sub-items otherwise) - https://github.com/TeamPneumatic/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/client/gui/GuiSearcher.java#L179-L182

So probably not much we can do here.  I'll drop FT into my dev instance and do some debugging to confirm this, though.

**Comment by desht** [comment]
Closing this, not a lot I can do here.
