### ISSUE TITLE
When drone picks up an entity, it acts like the entity it picked up.

### ISSUE THREAD

**Issue by yigitabi5444** [TeamPneumatic/pnc-repressurized#194]
Sevtech Ages

1.12.2

Forge 1.23.4.2707

pneumaticcraft-repressurized-1.12.2-0.6.6-192

when a drone picks up an entity, it stops following the program and it acts like the entity it picked up.

How to Reproduce:

program a drone to pick up a cow and go somewhere

after the drone picks up the cow, it stops

if you get close to it with wheat, it starts following you

İf you tell it to pick up zombies, it starts attacking you after it picks up a zombie

But the drone picks up players without a problem.

**Comment by desht** [comment]
Strange.  I tested with a drone picking a cow up, and although it didn't behave like the cow, it didn't work either - once the cow became a passenger, the drone just stopped (next piece in the program was a "Go To Location").

The Go To Location didn't execute because it believed the drone had no path to the destination (which it did - it was really close).  Is having a passenger somehow messing with the drone's pathfinding?  Investigating...

**Comment by MineMaarten** [comment]
This is fixed in the next version. It turns out that riding entities override the Drone's pathfinding (except for players because they off course do not have AI). We have a feeling this behaviour was introduced in Vanilla, possibly for horse/spider jockey handling maybe.

It is fixed now to preventing the entity from overriding the pathfinding.

**Comment by desht** [comment]
Fixed in 0.6.8 release
