### ISSUE TITLE
weird crash report

### ISSUE THREAD

**Issue by MasterSloth1** [TeamPneumatic/pnc-repressurized#195]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2705
### Mod Version
1.12.2-0.6.7-210
### Describe your problem, including steps to reproduce it
punched a rftools builder with a clearing quarry shape card in it.
### Any other comments?
i honestly dont know how pneumaticcraft is involved but the crash log says it is.
link to crash report
https://pastebin.com/idKeLYiW

**Comment by desht** [comment]
My suspicion falls on Fancy Block Particles (see the stack trace), but I will investigate a bit deeper...

**Comment by desht** [comment]
Actually, I just saw you have Optifine installed.  This is much more likely to be the problem.  In any case, I don't believe it's a PNC:R problem in any way (the block the client wrongly found could have been from any mod, or vanilla).  And since Optifine is present, all bets are off when it comes to attempting any kind of client-side debugging.

So there's not much I can do here, sorry.
