### ISSUE TITLE
Volume upgrades in standard machines

### ISSUE THREAD

**Issue by falizure** [TeamPneumatic/pnc-repressurized#225]
I just upgraded to the advanced pressure tubes and realized that the volume upgrade does almost no good in machines like the thermopneumatic processing plant, and infact most machines in general, it increases the amount of air the machine can hold but because processes involve pressure your safe range in machines is still between the same percentage of its volume, so your spending more resources for every bar of pressure, making it more expensive to start processing, and has no impact on the safety of the machine at high pressures, can we get a reinforcement upgrade or something that will actually allow the machines to operate at higher volumes of pressure safely? as it stands you have to ether stick with standard pipes or create a sub network of them separate from your advanced pipes, i seam to recal in past versions the volume upgrade did increase the safe operating range and im not sure if im remember wrong or why that was changed.

**Comment by desht** [comment]
No, there's no need to add any kind of reinforcement upgrade (and volume upgrades have never changed pressure thresholds in any way).  If safety is a concern, add a Security Upgrade to machines or Safety Module to tubes, which will vent air if the machine is over-pressure, but be aware that is basically wasting power.  It's better to use Pressure Gauge & Regulator modules to control the pressure in your system (and maybe Security Upgrades too as a failsafe).

Volume upgrade are not useless at all (although it's possible that a future release will increase the air capacity added per upgrade).  While it's true that most operations require a certain pressure level, and it's also true that a bigger volume means you'll be spending more fuel to get a machine up to pressure, what you seem to be missing is that pressure also *drops* more slowly per operation when you have a larger volume.

Consider: given a machine with a volume of 10000mL, and storing 50000mL of air, that machine is at 5 bar of pressure (50000/10000):

* Running some operation which costs (say) 2000mL of air will leave 4.8 bar in the machine (48000/10000).  So 0.2 bar has been used up.
* Now add 2 volume upgrades (for 5000mL each) bringing the volume to 20000mL.  Suddenly the pressure drops to 2.4 bar (48000/20000)
* However, running the same operation now (for 2000mL) drops the pressure to 2.3 bar, a drop of only 0.1 bar (instead of 0.2 bar before).

So the point of Volume Upgrades is to smooth out pressure changes when expensive operations are being carried out.  A good example would be the Assembly System with many speed ugprades - the pressure will drop very fast with 5-6 speed upgrades, and the system will stop with < 3.5 bar in the controller.  But add some volume upgrades to the controller, and you'll find the pressure drops much more slowly while the system is running.

**Comment by falizure** [comment]
ok that makes sense, thank you i assumed the security upgrade was only for player interference but if it also provides pressure releaf that will work

**Comment by desht** [comment]
Yeah, the name is a bit misleading and at some point (possibly not till 1.13 and a new major version of PNC) there will be a load of much better-named upgrades.  Right now a lot of upgrades get reused for multiple purposes.

**Comment by falizure** [comment]
Can their full functionality be listed in the ingame wiki mod? when looking at their tool tips it only lists the machines they work inside even the wiki mod, not their function, while mostly self explanatory that would help.

**Comment by desht** [comment]
I'll review the docs for IGW.  Also check the "Upgrades" side tab in the machine's GUI.  That should document the upgrades that each machine takes (I'll review that too and make sure it's accurate).

**Comment by falizure** [comment]
o the machine upgrades tab does work, thank you again :)
