### ISSUE TITLE
Crash on startup when using save game from earlier version.

### ISSUE THREAD

**Issue by remclave** [TeamPneumatic/pnc-repressurized#248]
Minecraft Version 1.12.2

Forge Version 14.23.4.2760

Mod Version  1.12.2-07.8-259 (_updated from 1.12.2-07.7-255_)

Crash report:
https://paste.dimdev.org/ifugivowis.mccrash

Copied saved game from earlier version of a modpack for which I am creating a quest book. The earlier

Issue is reproduceable. Update modpack to new instance on Twitch. Copy old save from older instance. Start new instance. Accept changes when launcher balks. Game crashes.

There is no crash when I start a new world. But I lose ALL my progress.

**Comment by desht** [comment]
Have you added any other mods since updating?  Looking at the stacktrace, the crash (CME) should never happen under normal circumstances.  Looks like something's modifying the semiblock list from another thread, possibly.

**Comment by desht** [comment]
Also, what changes exactly did you accept?  That suggests mods were also removed between the previous and current version of your pack - which mods?

Do you know what semiblocks (logistics frames, heat frames, crop supports, spawner agitators) were in your world, and were any of them on a block that is no longer present in your new instance (due to mod removal) ?

**Comment by desht** [comment]
Closed due to lack of response.

**Comment by remclave** [comment]
I do apologize for missing this follow-up query. The mod pack author switched out one mod pack for another which was responsible for the crash. At the time I was unaware that this change had taken place. I am paying more attention to updates for that pack to (hopefully) prevent further confusion.
