### ISSUE TITLE
Disappearing Drones While Using Dig Command

### ISSUE THREAD

**Issue by furrious** [TeamPneumatic/pnc-repressurized#250]
### Minecraft Version
1.12.2
### Forge Version
forge-14.23.4.2747
### Mod Version
0.7.5-248
### Describe your problem, including steps to reproduce it
On a server, a simple program with just an "import from inventory" command to pick up a pick and shovel and a "dig" command will inevitably result in disappearing drones. I've tried in multiple parts of the map, drone with/without upgrades, and with and without a charging station with a dispenser upgrade nearby, nothing seems to make a difference. The drone will dig an unknown number of blocks, freeze for a little while (as if it's calculating), and next thing I know it just isn't there any more. It seems to be the same as #Issue 240, which has already been closed. Unfortunately, I have yet to be able to reproduce this in single player.

**Comment by desht** [comment]
Does anything appear in the server log when the drone disappears?

**Comment by furrious** [comment]
I asked the server admin to check for me, and he couldn't find anything, unfortunately. I actually delayed quite a while putting this on here, since it didn't seem like it would be too useful for you without any other data, but after the sixth drone in a different part of the map disappeared I decided post it. I will continue trying to reproduce it, but I at least wanted to let you know that it's happening (even if it is a fringe case).

**Comment by desht** [comment]
OK, thanks.  I will see what I can do to reproduce it, but without any server logs it will be difficult to know what's going on.  I feel like there may be another mod at work here possibly cleaning up entities, but it's hard to say.

I do believe it's a real problem since you're not the first to report it, but so far I've not been able to track it down.

As a workaround, you could try using the Programmable Controller, which can run most of the programs a real drone does, and has the advantage of not using real entities (the little drone is client-side only), and is lighter on server CPU too.

**Comment by Wicked7000** [comment]
Just as an added note I'm having a similar issue where the drone is being destroyed without the usual log message (that says why it was destroyed), this happens very frequently and I've had to remake the drone multiple times. I'm pretty sure this is caused by another mod doing things with entities but I'm unable to pinpoint anything by looking at logs. (Nothing is really present in the logs that point to it), this is happening in ProjectOzone3.

**Comment by desht** [comment]
PO3 is 1.12.2, which is unsupported, sorry.  It's very likely some other mod is removing the drone entities, but I'm not going to be investigating or changing anything for PNC on 1.12.2.
