### ISSUE TITLE
Liquid Compressor won't burn gasoline

### ISSUE THREAD

**Issue by DungeonMaestro** [TeamPneumatic/pnc-repressurized#257]
Minecraft 1.12.2
Forge 14.23.5.2769
PC:R 0.8.1-274

Is the Liquid Compressor not intended to run on Gasoline? I'm pumping Immersive Petroleum gasoline into the block and while the machine accepts the fluid into its tank it doesn't consume fuel or produce pressure. Redstone is set to always, connected to a working pressure system, IP Diesel works fine. The compressor doesn't even list gasoline as an available fuel. If this is intentional is there a way through Crafttweaker or the PC:R config to add it to the fuel registry?

**Comment by desht** [comment]
We don't register IP's fuels but Diesel will work because PNC:R has native Diesel (fluid name "diesel" is shared with IP).

Anyway, accepted fuels can be tweaked via CraftTweaker: see  https://crafttweaker.readthedocs.io/en/latest/#Mods/PneumaticCraft_Repressurized/LiquidFuels/

I'd recommend a value of 1500000 (that's mL of air per bucket of fuel), but that's up to you.  1500000 is what PNC:R's own "fuel" liquid produces.

I can add support for IP's gasoline in the next release; that's easy enough to do.

**Comment by desht** [comment]
Added in 0.8.2 release
