### ISSUE TITLE
Aerial Interface with Dispenser Module is not charging Pneumatic Armors

### ISSUE THREAD

**Issue by Minamikaze392** [TeamPneumatic/pnc-repressurized#278]
Minecraft Version 1.12.2

Forge Version 14.23.5.2768

Mod Version 1.12.2-0.8.3-299

So I just updated the mod today to the latest version from 1.12.2-0.7.8-259, and I found that the aerial interface is not charging the pressure of my armor, unless I take off the dispenser module from it. Before updating the mod it was fine with or without the dispenser module. Not sure if this change is intended though.

**Comment by desht** [comment]
Yeah... that was an unforeseen side effect.

The intention was that the Dispenser Upgrade switched between "items" mode and "food/xp" mode.  However, due to a quirk in versions previous to 0.8.0, accessing the top face of the interface always gave access to the armor inventory, even with a Dispenser Upgrade (note that in 0.8.0+ you can choose which sides of the interface are connected to which part of your inventory via a new GUI side tab).

Since that was previous behaviour and I don't like arbitrary nerfs, I think it would be OK to restore that specific behaviour in 0.8.0+: accessing the top face will give access to the armor inventory even with a Dispenser Upgrade installed, *if* the top face is connected to your armor.

The alternative is to have two Aerial Interfaces: one with a Dispenser for food & xp, and one without for item access (including charging).

**Comment by Minamikaze392** [comment]
Ahh it will be ok if this is an intended design. Making an extra aerial interface is not a big deal, I have no problem with that. Let's just treat this issue as old version players not being familiar with new mechanisms :)

**Comment by desht** [comment]
I'm not convinced about allowing the Dispenser Upgrade to unlock extra functionality (effectively allowing all types of resource to be interfaced at once), but I will think about it.  It would certainly not be before the next major release, and possibly not till 1.13, since it's a significant change.  The Dispenser Upgrade was always intended as more of a sidegrade than a straight upgrade.

**Comment by desht** [comment]
Older pre-0.8.0 behaviour restored in 0.8.4.  Top face can again be used to charge armor even with dispenser upgrade inserted (iff the top face is configured for armor).
