### ISSUE TITLE
Suggestion: config option to disable natural heat sources

### ISSUE THREAD

**Issue by wormzjl** [TeamPneumatic/pnc-repressurized#293]
The purpose is to enforce the use of vortex tube instead of some smart systems that take advantage of natural heat sources.

**Comment by desht** [comment]
This could be an option, but my concern would be the potential confusion arising from inconsistencies in PNCR behaviour between different instances/modpacks.  Any deviation from the default would need to be very clearly documented as such (e.g. in a quest book or other modpack documentation).

Having said that, this wouldn't be too hard to add, more likely by a configurable thermal resistance rather than a simple on/off toggle.

Note that the thermal resistance of fluids is already configurable: see ``D:fluidThermalResistance`` in the config file.  Setting this to a very big number would make heat move so slowly from fluids that it would not be worth using them.  This doesn't apply to solid blocks (torches/fire/magma), unfortunately, but that or something similar could be added easily enough.  Although torches already have a stupid high resistance (100000) so don't do much.

**Comment by wormzjl** [comment]
If it can prevent the refinery from reaching 100°C by all means then I think it will be ok.

**Comment by Sewef** [comment]
I'd say put a ThermalResistance of -1 to disable this block/fluid from producing heat

**Comment by desht** [comment]
@Sewef not that simple, unfortunately.  The rate that heat moves between two objects (the machine, and the block/fluid) is dependent on the sum of both of their thermal resistances.  So just setting the block/fluid to -1 would make heat transfer a little *faster*.

**Comment by desht** [comment]
Added in 0.9.0 release: see ``D:blockThermalResistanceMultiplier`` in config

**Comment by wormzjl** [comment]
Will this affect the thermal conductivity of normal PnC blocks?
