### ISSUE TITLE
[Question] Remote to control program flow problem

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#330]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2768-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.3-337
### Describe your problem, including steps to reproduce it
![image](https://user-images.githubusercontent.com/4198031/56460029-9bb6b080-639c-11e9-8c9c-24bf8fd250c9.png)

I've copied the program from the book to use the remote to control an universal sensor and wanted to use the same program to control a drone.

In the above screen shot you can see that the condition looks strange.

My question is how can a drone be controlled with a check box on a remote? Is it possible to see the value of variables?

Many thanks

**Comment by desht** [comment]
Could you pastebin your program so I can load it up and examine it?

**Comment by duncanwebb** [comment]
No problem, here you are.
drone program
https://pastebin.com/aRSZZtqd
remote program
https://pastebin.com/xhjrtL57

**Comment by desht** [comment]
OK, I think I see what you're attempting here.

The main thing to remember is that remotes can only manipulate *global* variables, so in your drone program, you should use `#signal1` rather than `signal1`.  `signal1` would be a local variable to the drone in question.

Also, since the remote only affects the X coordinate of a variable, it's not necessary to include Y & Z in the condition puzzle piece (although it shouldn't do any harm).

As far as viewing variable values, there are a few options:

* Display them on the remote via a label (which you do in your example)
* A Sign Edit puzzle piece can use variables with the same `${var}` or `${#var}` so you can write variable values to a sign or aphorism tile
* A Drone Rename puzzle piece can write the variable name into the drone's name

**Comment by duncanwebb** [comment]
Many thanks, It was the global/local variables that I didn't realize that there were local and global variables.

I'm guessing that a checkbox only effects X and buttons can set any value.

I like the edit sign component most as it provides a confirmation independently from the remote and can display multiple variables. This is explained in the coordinate operator widget but I find reading on screen hard compared to reading a page of A4.

Thanks again for you help.

**Comment by desht** [comment]
Yes, the checkbox widget only affects the X value, and buttons can set any or all of X,Y,Z depending on what you configure in the Remote GUI editor.

Any other remote questions?  Or is this good to close now?

**Comment by duncanwebb** [comment]
Sorry I should have done that.
