### ISSUE TITLE
Logistics Frame cannot be places on IE barrels

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#333]
### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2768-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.3-337
### Describe your problem, including steps to reproduce it
I cannot place logistics frames on immersive engineering barrels. This works in pneumaticcraft-repressurized-1.12.2-0.9.4-1.
### Any other comments?
I had some frames already on barrels and when the barrel was broken the frames were dropped but an image of the frame remained until the game was reloaded.

**Comment by desht** [comment]
This is almost certainly down to changes in 0.10 where frames are much more side-aware now - you'll probably notice that one side of any frame now has a semi-transparent highlight.  This tells logistics drones which side of the inventory they should attempt to interact with (which can be fairly important for sided inventories).

In my testing I can see that frame can only be placed by clicking them on the *top* or *bottom* faces of a barrel; this is due to the barrel only providing/accepting fluids from those two faces.  Clicking the frame on the side of a barrel just opens the GUI.

This is actually correct behaviour, although I appreciate it causes some confusion.

Regarding the image remaining, that sounds like a client desync issue, which might be difficult to track down.  Possibly related to the frame having an invalid face from the previous world, but I'm not sure...

In any case, can you check that you can place frames on the top or bottom of a barrel and let me know?

**Comment by duncanwebb** [comment]
Yes that was it, placing the frame on the top side worked. Breaking the block now works as expected and doesn't show the frame.

I had noticed the new tabs on the sides of the frame. Hadn't noticed the highlighted side, tricky to see on grey blocks. Did notice the chest has a shaded front face but hadn't realized what that meant. On the refinery the default is up so I didn't see this.

I think you're correct about the invalid face.

Thank you again
