### ISSUE TITLE
Patrol widget

### ISSUE THREAD

**Issue by Sendir** [TeamPneumatic/pnc-repressurized#390]
A new widget idea yey~ Remember how I earlier in a post I said I like to see things moving around? Why don't we get the "patrol widget" and as the name implies it just makes the drone move from point A to B but we already have that with the "go to" one so the difference? This one grabs the entire area we set it to, picks a random coordinate and moves to it then waits a random amount of time (between 1-5 seconds? maybe configurable or even 0 seconds) and moves to another random location just so we see them flying around instead of standing still like the defense drone that really only stands up when it's time to kill. We can get a similar effect with a row of "go to location" widgets but not only is that tiring to get all the GPSs to it but we get some problems, 1: The path is always the same so after a while it gets boring, it makes it seem way more robotic that it needs to be (why am I complaining about robotic moving on a robot o.e) while the random one keeps that "wounder" effect of walking along and suddenly it flies in front of you when you didn't expect it.

Problem number 2: I am thinking of using this mainly on a defense drone so if I have a long (12 widgets of "go to location) path set for it and a mob walks in to range just as it was about to start the path then it needs to cycle through it all before it deals with it so it does ruin the purpose...

Final saying

- This widget is a low priority one so all other widgets will take over the moment they can, kind of like the "stand by" one, I'm assuming it works in a similar matter.

**Comment by desht** [comment]
A neat idea, but probably not till 1.14+.

**Comment by ChocoPuppy** [comment]
Couldn't you get the exact same effect just by using a normal goto widget and setting the Area type to Random? Then it'll just pick a random point in the area you selected and go to there, which sounds like what you described.

or, if you wanted to have a set path without making individual gotos for each of the positions, why not just use a For Each Coordinate piece to call one Method with a goto piece set to the coordinate from the For Each piece (and an Attack piece for the whole area or maybe just a spherical area around the drone if you want to make the patrolling seem more like it's actually "spotting" enemies instead of randomly beelining for an enemy halfway across the map)

**Comment by desht** [comment]
Gonna close this since patrolling is really something better done with a program, not a single widget.
