### ISSUE TITLE
Agitated slime spawner abnormal behavior

### ISSUE THREAD

**Issue by Tlotro** [TeamPneumatic/pnc-repressurized#404]
Minecraft Version:
1.12.2
Forge Version:
14.23.5.2838
Mod Version:
1.12.2-0.11.5-371

Problem: 
1) Agitated slime spawners spawn only small slimes, but with HP of properly spawned ones. After being hit they don't die, but go to half of a heart. Other mods define them as small.

2) Spawner gets permanently stuck in that state even after removal of the agitator.

How to reproduce:
1) get a slime spawner
2) use a spawner agitator on it
3) wait and observe

**Comment by desht** [comment]
Can't reproduce this, sorry.  The spawner behaves exactly the same whether or not an Agitator is attached - spawns small slimes, they die as normal.

This makes sense because the Agitator doesn't spawn anything itself; all it does is force-tick the mob spawner even if a player isn't in range (within 16 blocks).  All the spawning is still handled by the mob spawner itself.

I think you may have another mod interfering possibly.  If you can reproduce this with only PNC:R installed that would  be good to know.

**Comment by desht** [comment]
Closed due to lack of response.
