### ISSUE TITLE
addDrillLaserRecipe(Input, Output) Not functioning

### ISSUE THREAD

**Issue by MappaCrappa** [TeamPneumatic/pnc-repressurized#418]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
1.12.2-4.4.22.2-build.0405
### Mod Version
1.12.2-0.11.8-380
### Describe your problem, including steps to reproduce it
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;   
mods.pneumaticcraft.assembly.addDrillLaserRecipe(</minecraft:dirt/>, </minecraft:diamond/>);
A test to add a recipe for diamond from dirt doesnt work. Nor does any other recipe with addDrillLaserRecipe using Crafttweaker. It provides no errors. I've looked up the handler with dumpzs and it's the same as written here. If I change the handler, it correctly identifies I've made an error, yet I cannot get the correct handler to work.
### Any other comments?
Solely this handler doesn't seem to work. DrillRecipe and LaserRecipe work as intended.

**Comment by desht** [comment]
It's not supposed to work. Combined drill/laser recipes are auto-created from the existing drill and laser recipes.

**Comment by desht** [comment]
Just to expand on this: assembly drill/laser recipes are dynamically computed after the separate drill and laser recipes are added.  If there's a drill recipe for Item A -> Item B, and a laser recipe for Item B -> Item C, then a drill/laser recipe will be added for ItemA -> Item C.

The "addDrillLaserRecipe" CraftTweaker method was added in error way back when I accepted the PR for CT support, shortly after I took over maintenance of the mod.  Neither I nor the PR author properly understood the system then, so that method should never have been added. If you check your server log, you should see a message like:

```addDrillLaserRecipe() does not do anything: drill/laser recipes are automatically calculated from drill and laser recipes. This call will be removed in the next major release```

**Comment by MappaCrappa** [comment]
That's for the explanation! Ps. Love the mod :)
