### ISSUE TITLE
Suggestion: Allow the compressor to compress gas other than air

### ISSUE THREAD

**Issue by wormzjl** [TeamPneumatic/pnc-repressurized#430]
Note that this is just something from a modpack maker's perspective to make more complex and realistic mechanisms.
What I have in mind is to make "air" an actual fluid, and allowing PnC compressor to compress all forge fluids.
I understand this will touch the basic framework of this mod. But in a well designed modpack, this can bring the gameplay to another level. For example: performing compression crafting in pressure chamber with different gases, and combining with https://github.com/TeamPneumatic/pnc-repressurized/issues/398, it is possible to add air distillation under pressure like IRL (5-10 bars).

**Comment by desht** [comment]
"Touch the basic framework" is a bit of an understatement :)  Pressure in PNC:R is the mod's power system in effect, so turning that into a fluid would be like asking an RF-using mod to turn RF into a fluid... it doesn't make an awful lot of sense.

Bear in mind that the Thermopneumatic Processing Plant can already do part of what you need (turn a fluid and/or item into another fluid, given pressure and/or heat).  And in 1.14.4, the TPP will also be able to create an optional output item in addition to (or instead of) the output fluid.

So although this is a neat idea, I'm going to have say no... it's just not practical.

**Comment by wormzjl** [comment]
ok nevermind :)
