### ISSUE TITLE
some sort of nonfatal liquid registry conflict between this and BuildCraft

### ISSUE THREAD

**Issue by macks2008** [TeamPneumatic/pnc-repressurized#435]
### Minecraft Version
1.12.2
### Forge Version
14.23.5 .2847
### Mod Version
0.11.7-371
### Describe your problem, including steps to reproduce it
I'm not sure whose side of the fence this is on, but when I try adding the latest version of BuildCraft (7.99.24.5) to a world that already generated with PneumaticCraft's oil, all of the oil pools are removed by FML due to liquid:crude_oil no longer being registered. I brought this up to the BuildCraft team on their discord server, and they told me it was probably on your side of the fence because you remove your liquid when another oil is detected; thus, here I am.
Unfortunately, I don't know which log file is from when I tried adding DC (it was a few launches ago but I don't know which lunch), or I'd share that. I'll try to figure it out tomorrow when I'm on the computer that I test mod additions on, or if I can't I'll try adding the mod again to generate another blog. For now though... no log 
### Any other comments?
Thanks for making this port? Always loved PC

**Comment by desht** [comment]
Yeah... this has sadly been the case since the 1.12.2 port - see also #65 

PNC:R will just use Buildcraft's oil if it finds it already registered on startup (as the fluid called "oil").  Problem with that is the fluid blocks that make up oil lakes becomes invalid, and there's no easy workaround or fix for this.  One of the hazards of adding mods to a world after generation and a limitation of the 1.12.2 fluid system :(

All this goes away in 1.14.4+ where fluids are proper namespaced registry objects, although I appreciate that doesn't help much here...

**Comment by Rongmario** [comment]
Another case: https://github.com/e99999/GT-Classic/issues/133

**Comment by desht** [comment]
No.
