### ISSUE TITLE
Missing Texture for new TPP Move Fluid button

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#450]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.13-394
### Describe your problem, including steps to reproduce it

Seems like the button texture just isn't there. The original, seen when holding shift, still is, however.

![Missing Texture](https://user-images.githubusercontent.com/9543430/79597687-bc4d3f80-80b0-11ea-8da7-750d7275e9c1.PNG)

![Holding Shift](https://user-images.githubusercontent.com/9543430/79597689-bc4d3f80-80b0-11ea-8104-7dab629567ea.PNG)

### Any other comments?

**Comment by desht** [comment]
Yeah, mistake on my part... forgot to push that new image to github. Oops. Will sort it for the next release.

**Comment by MuteTiefling** [comment]
Happens! Sorry for the bug report spam for 1.12, I've just been doing a lot of testing here. I guess I ought to toss together a 1.14 pack do the same there to help out where it's more relevant, eh?

**Comment by desht** [comment]
Yeah, some testing for 1.14.4 would be cool :)  Actually, I'm really really close to a 1.15.2 release, and that's where all the interesting new development is going to happen (although there's already quite a lot new in 1.14.4, I'm really only going to aim for stability there now - no more major new features on that release).

Anyhow, this particular issue is fixed in 0.11.14 release.

**Comment by MuteTiefling** [comment]
I look forward to a 1.15 release and will play the heck out of it. Been wanting a good reason to jump to a later version and all the features you have planned would definitely be one. I'll keep an eye on Reddit for your announcment :D
