### ISSUE TITLE
Datapack Recipe Creation for Machines

### ISSUE THREAD

**Issue by hotdog95** [TeamPneumatic/pnc-repressurized#472]
### Minecraft Version
1.14.4

### Forge Version
28.2.6

### Mod Version
1.0.2-11

### Describe your problem, including steps to reproduce it
There is no possible way of adding new recipes for the various machines, I noticed that in the latest 1.15 build, you added recipe type "pneumaticcraft:thermo_plant" this does not function for this build

Trying to replace recipes also does not work, they seem to be fixed into what was generated and cannot be overridden.

**Comment by desht** [comment]
It is absolutely possible to add new recipes, though I haven't documented it well yet (something I do intend to do).  Note that 1.14.4 uses a slightly custom system because I hadn't figured out adding new vanilla recipe types back when I did that port.  1.15.2 uses a much more standardised system based on the vanilla recipe system, but I do not plan to backport that to 1.14.4.

To add a new recipe in 1.14.4, place your .json in `<datapackname>/data/pneumaticcraft/pneumaticcraft/machine_recipes/<machine_name>/<recipename>.json`

You can see all of the default recipes here: https://github.com/TeamPneumatic/pnc-repressurized/tree/1.14/src/main/resources/data/pneumaticcraft/pneumaticcraft/machine_recipes

To override a recipe, add a recipe of the same name in your own data pack.  Adding an empty JSON document with the same filename will disable the recipe.  (By empty, I mean `{}` rather than an empty file).

See also https://github.com/TeamPneumatic/pnc-repressurized/issues/454 where another player is successfully using custom recipes.

**Comment by hotdog95** [comment]
Ok thank you, I managed to create the recipe I wanted, turns out I needed to include a fluid input, however I still wasn't able to disable any recipe, this doesn't worry me as that was not my goal, but I thought I'd let you know

**Comment by desht** [comment]
I've added a bunch of docs here: https://github.com/TeamPneumatic/pnc-repressurized/wiki
