### ISSUE TITLE
Glass Elevator caller crash

### ISSUE THREAD

**Issue by UltimateFisher** [TeamPneumatic/pnc-repressurized#497]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
.31.1.74
### Mod Version
1.2.0
### Describe your problem, including steps to reproduce it
I tried to use the camo tool on an elevator caller to make it pressurised glass. now whenever it renders the game immediately crashes. 
### Any other comments?
[crash-2020-05-20_22.19.50-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4660450/crash-2020-05-20_22.19.50-client.txt)
It didn't crash the server just people trying to render it.

**Comment by desht** [comment]
This will be fixed in the upcoming 1.2.1 release but if you need to get going again in your current world, you can get build 22 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ which has the fix applied.

Note that it will render the Pressure Glass OK now, but connected textures won't work for blocks camo'd as Pressure Glass (that requires model properties only present in real pressure glass tile entities, not camouflaged blocks).

**Comment by UltimateFisher** [comment]
its not crashing anymore thank you. but it causes a seeing through world bug
![2020-05-21_12 57 04](https://user-images.githubusercontent.com/65625520/82590021-9b21b800-9b62-11ea-87ba-858b6c785f7e.png)

**Comment by desht** [comment]
That'll be fixed in the next release too.

**Comment by desht** [comment]
Fixed in 1.2.1 release
