### ISSUE TITLE
Drones getting stuck on pipes

### ISSUE THREAD

**Issue by Lanternglow** [TeamPneumatic/pnc-repressurized#520]
Minecraft Version 1.15.2
Forge Version 31.2.0
Mod Version 1.2.2-30

Describe your problem, including steps to reproduce it
I was running Pneumaticraft 1.2.1-25 yesterday and things were fine. I have a refinery with a logistic drone automatically storing the various oil products into their own tanks. I also have a farm being tended by a harvesting drone. Both of them have charging stations nearby that they go to as needed.

Today I upgraded to 1.2.2-30 and the drones suddenly became very stupid. They keep getting stuck on the pressure pipes in the area. It seems that their pathfinding logic is ignoring the blocks with pipes in them and trying to route the drone through those blocks anyway. This persists even if I apply camouflage to the pipes so that they are seen as full blocks.

Any other comments?
Through some creative re-routing of the pipes I have managed to convince the drones to stop crashing into them. But I thought I would let you know that this happens. My gut instinct suspicion is that it has something to do with the new heat insulation block and needing to change the pathfinding code so that the drones are willing to reach through those to get to things. But I haven't looked through your code to check that, so what do I know?

**Comment by desht** [comment]
Yeah, try 1.3.0, out in beta. I made some fixes around pathfinding on that release...

**Comment by desht** [comment]
A bit more info here:
* Thermal Lagging isn't the cause of the problem, rather this commit: https://github.com/TeamPneumatic/pnc-repressurized/commit/3d2fe0fcc430760455209d1fbc072ce1294e4f77
* Thermal Lagging has no hitbox (unless you're sneaking or holding a wrench or pick) so drones can reach through it fine.
* The path bug I introduced in the above commit should be fixed in 1.3.0, by https://github.com/TeamPneumatic/pnc-repressurized/commit/21ed59b1c51e2ac3e70bdf9aff86bb00600f6088

Would be interested to hear if 1.3.0 does indeed fix your problems.

**Comment by Lanternglow** [comment]
Yes indeed. I am not seeing any problems with logistic drone trying to fly through the pressure pipes near my refinery in 1.3.0-33
