### ISSUE TITLE
Feedback: Base Fuel balance feels off

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#554]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.15.2-1.4.0-53
### Describe your problem, including steps to reproduce it

Not a bug, but the basic fuel balance feels a bit off since Ethylene was added as a default fuel. It's equivalent to LPG, so it makes for a fairly easy comparison in terms of value.

I did some testing and one bucket of LPG in an Advanced Liquid Compressor generated about 1.7 million mL of air. 
A single bucket of Ethylene used to generate RF in a gas burning generator and then power a Flux compressor ended up generating about 4.1 million mL of air. 

Now, that's already a pretty massive difference in output for fuels that are listed as equivalent. But the gap widens more when you consider that a flux generator can easily run with only passive cooling (just a bunch of heat sinks) with 9 speed upgrades. That's generating 1450 mL/t. An Advanced Liquid Compressor with the same amount of passive cooling can really only run at 4 speed upgrades for about 316 mL/t. So not only is the output higher by going through the Flux compressor, but it's considerably faster too.

Granted, speed is rarely a concern, at least as far as I've seen after many hours of play with the mod. I've never built anything with PNC that requires a ton of air per tick, so even though I always feel compelled to build fast compressors, a slow one is generally more than sufficient. For instance, I recently did a lot of disenchanting in my play world, a single Advanced Liquid generator kept up with me easily, despite running hundreds of disenchants through a pressure chamber over the coarse of a few hours. It burned a lot of fuel, but I never had to wait on pressure. The real difference comes down to cost of the overall build. For the same generation rate between liquid and flux compressors, I need significantly less cooling for the flux compressor, which makes it cheaper to build. I could have run that flux compressor at a much lower speed and saved myself a load of compressed iron in the form of heat sinks and heat pipes. 

Then there's another consideration to make... and I know your roadmap does address this, but oil is not renewable in any way that can be automated. Sure, if you have access to a decent source of emeralds it can be purchased very easily through Amadron, but there's no set and forget method of getting oil without another mod. Compare that to many RF power systems that can have their entire supply chain automated (Ethylene being a great example where it just needs a steady supply of crops and water). 

I personally don't mind that it can't be automated. It can at least be gathered in bulk manually and lasts a fairly long time. The gas lift is great early on and emeralds are easy to obtain with a raid farm or villager trading. Or even just by trading regularly on Amadron. But there doesn't appear to be any positive here. LPG is harder to obtain, requires more cooling infrastructure and ends up being slower as a result, and generates far less than an equivalent fuel going through an extra conversion step. 

### Any other comments?

I'm not really sure what the solution is here short of simply nerfing ethylene or reducing the rate at which heat is generated by liquid compressors. I certainly do not advocate joining in on the arms race mentality that permeates the world of RF based mods and simply buffing LPG. But LPG and liquid compressors in general feel like they're at a severe disadvantage compared to the flux compressors, which feel like they should be there to ease cross mod compatibility rather than to be the best in class. It seems like there should be a reason to use LPG over RF. 

Or perhaps not? Am I wrong in that assumption? Am I making an issue out of something that's intended? Are flux compressors the compensation to the player for having made it all the way through PCB production?

**Comment by desht** [comment]
A lot of valid points here, and I'll address the easiest one first: biodiesel is the next major feature I plan to work on (the temperature gauge change was a prelude to that since the the TPP will need some careful temperature control for yeast fermentation etc. to work well).

But yeah, the Flux Compressor has always been a bit too good.  IIRC even MineMaarten wasn't too happy about it back when he added it, and the overheating mechanic was specifically added as a balance to how good it is.  But it's still too good.

Not sure what the best approach is here.  Maybe a slight nerf to the Flux Compressor combined with a slight boost to Advanced Liquid (and Solid) Compressors?  It's interesting that the FC needs so much less cooling than the other tier 2 compressors; I'll check into that.  Ideally the heat generated vs. the air produced should be equivalent for all of them, but if the FC is significantly better, that could be a place to start.

Note that with 9 speed upgrades, the FC does require nearly 4000RF/t to run, so you also need some non-trivial RF production. Regarding Ethylene in the gas-burning generator, that's a block that's well known for producing ridiculous amounts of RF (up to nearly 8000RF/t), so that one is at least partly on Mekanism :)

Out of interest, what's your heat sink setup to keep the FC temperature stable with 9 speed ugprades?

**Comment by MuteTiefling** [comment]
Yeah, I'll concede that Mekanism isn't the best thing to compare against as it's got pretty high power production (and to be somewhat fair to it, also uses a fairly huge amount of energy in some cases, like high tier ore processing). Still, I'd argue that 4k rf/t isn't that difficult to attain with most tech mods. That's a single bio diesel generator from Immersive Engineering, for instance. 

I was kind of thinking last night that heat might be the way to solve this imbalance, and after thinking about it more, I think that it may be the best approach. I had forgotten that you were planning on fine heat control for the yeast mechanic, but perhaps that same thing would fit here. In essence, each compressor has an optimal operating range, but if you go above or below it, efficiency drops rapidly. 

For example, solid fuel could be most efficient at 100-300 degrees. So there's a bit of a hump to get over in terms of ignition, but also an easier range to maintain to offset it's lower output and inability to provide fine control (since it keeps producing for the entire burn time of a piece of fuel). Liquid fuel would be more efficient at a narrower but also lower range. Perhaps, 50-150 degrees, representing it's ability to be vaporized internally to make it easier to ignite.  And then the flux compressor would have a very narrow safe operating range, like say... 10-30. Outside of that the electronics act up and efficiency drops. This would mean it would require active cooling in almost all circumstances to be optimal. Similarly, the solid/liquid fuels would actually be inefficient until they've had a chance to warm up a bit, so you'd either want to keep them heated or make sure they run for longer time periods by setting up an RS Latch to power them on at low pressure and off at high. This also adds some value to having volume upgrades in a system as it means you've got a longer burn period. 

As for the passive cooling setup, I've done it a few ways, but in my testing world I set it up in a cold biome with a 5x5x2 block of heat pipes off either side, covered in heat sinks. That keeps it perfectly balanced at the 100% threshold. In my previous play world I didn't go quite so big, but it was still running at 97% efficiency. Actually, if you recall the images from the Quantum Entangloporter thread, that was the one running at 97%. It still used a lot of iron, but it was probably about half what I threw at this test setup. 

![2020-07-21_07 04 48](https://user-images.githubusercontent.com/9543430/88048125-bf792100-cb20-11ea-829d-166b46bcbb9d.png)

In fact, even with 5x5x1 blocks of heat pipe, it's still 99% efficient.

![2020-07-21_07 58 45](https://user-images.githubusercontent.com/9543430/88052279-0585b300-cb28-11ea-86bc-e64b1a577d36.png)

**Comment by MuteTiefling** [comment]
> Ideally the heat generated vs. the air produced should be equivalent for all of them

Just had a thought, but this might actually be the main reason why FC is so much easier to cool. It's got a lower initial mL per tick than LPG in a liquid compressor, so the heat wouldn't scale up as fast as speed upgrades are applied. Maybe a simple fix to this would be to make the heat generation a fixed value per tick across all of the compressors. Or at the very least decouple it from the mL/t.

Without speed upgrades, a Liquid compressor with LPG is doing 62.5 mL/t of air and the FC does 15. If both generate x heat per operation, rather than per mL of air, the Liquid compressor is automatically put back on top as the better compressor since it'll be doing more air with less cooling needed. Even the Advanced Air Compressor comes out better than the FC in this scenario, as it does 50 mL per tick.

**Comment by desht** [comment]
Hmm, that's definitely worth investigating a bit more... thanks for the insight.

**Comment by desht** [comment]
Just got back to this and yes - the flux compressor is too good!

Tested base setups for a Flux & AdvLiquid compressor (no upgrades):
* Flux produces 16 air/t and 0.4 heat/t  - 40:1 air:heat ratio
* AdvLiq (with LPG) produces 62 air/t and 3.1heat/t - 20:1 air/heat ratio

So the Flux Compressor produces half the heat that the liquid compressor does.  The simplest approach here, I think, is just to make the Flux Compressor produce twice the heat it does now.

What I plan to do is calculate the heat produced as simply `air_produced / 20.0`, for all compressors which produce heat, regardless of speed upgrades etc.  Which won't change anything for the Advanced Compressor & Advanced Liquid Compressor, but bring the Flux Compressor in line with those two.  It will also have the effect of slowing heat addition a little as efficiency drops due to heat, but I don't think that will be a problem.

(One other minor change is that all compressors were rounding down air produced to the int value.  E.g. if a compressor produces 25.5 air/t, it only counted as 25 air/t.  I'm fixing it so that 0.5 air/t doesn't get lost - small change but it will add a little more fuel-to-air efficiency).

**Comment by desht** [comment]
Build 12 should bring the Flux compressor more in line with the advanced liquid and solid fuel compressors, as detailed above.

**Comment by MuteTiefling** [comment]
Might be a bit before I can test this out, but I'll be sure to let you know once I can. I'm just far enough in my new 1.16 world to potentially see how it feels in survival.

**Comment by desht** [comment]
Rebalanced in 2.1.1 release.  Closing for now; feel free to reopen if you still find some issues when you test.

**Comment by MuteTiefling** [comment]
Finally came back to test this a bit more and this does feel a lot better. The flux compressor is still very good, but it's much more in line with the liquid ones now and I can't run it nearly as fast with passive cooling as before.
