### ISSUE TITLE
Progwidget - Unable to read redstone from lever attached to a transparent block

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#560]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.4.3-59
### Describe your problem, including steps to reproduce it

Bit of an edge case, here. I've got a lever on a camo block that's covering a redstone module. That module module is meant to control something further down the line. I want a drone to control the lever conditionally. I don't want it to toggle blindly, so I check the redstone level of the lever to know if it needs to be toggled from it's current state.

That condition fails to read the lever on a camo block. A lever on a regular block works fine, however. 

### Any other comments?

https://streamable.com/83gr9o

**Comment by MuteTiefling** [comment]
Actually, it's transparency that's the kicker. So I can reproduce this if the lever is on vanilla glass too, not just on a camo block.

**Comment by MuteTiefling** [comment]
Also, quite a simple work around is to just have the redstone module read the block redstone, rather than have the lever on a camo block. The drone can then read the lever fine and the redstone is still transmitted into the tube network.

**Comment by desht** [comment]
I don't think there's any simple fix for this, simply due to the way vanilla redstone mechanics work.  When the drone inspects a block for its signal level, what it's actually checking is how much power the block is getting from its 6 neighbouring blocks, not how much power the block is emitting (which would actually be rather more difficult to measure, believe it or not).

It looks like "normal" solid blocks pass the signal they get from the lever back to the lever, so the drone sees a signal on the lever.  But I presume that glass blocks don't do that, so the lever doesn't appear to be powered.

The correct workaround (arguably not even a workaround but the correct behaviour) is indeed to target the block that the lever is attached to rather than the lever itself.

Gonna close this since I don't think there's much I could do about it short of some major (possibly breaking) changes to how drones measure redstone levels.
