### ISSUE TITLE
Heating Frame voiding Mekanism Tanks

### ISSUE THREAD

**Issue by ben-mkiv** [TeamPneumatic/pnc-repressurized#562]
### Minecraft Version
1.16.1

### Forge Version
doesn't matter

### Mod Version
2.0.0.4

### Describe your problem, including steps to reproduce it
1.) place heating frame on chest and cool it down
2.) put a tank with molten plastic in it (ideally with several buckets of liquid in it)
3.) wait for your tank to get voided and to realize that you only got plastic sheets for one bucket of molten plastic instead of the amount of liquid in the tank

(I've only tested with mekanism tanks, ~~but it's probably the same issue for any kind of container~~)

### Any other comments?
The heating frame worker should test if an Item has a Fluid Capability and should only extract the amount of liquid that can be processed

The (empty) tank should remain in the inventory

**Comment by desht** [comment]
Actually, this is a problem specifically with the Mekanism tanks, because their tank item does not override `hasContainer()` and `getContainer()`.  The problem does not occur with either PNC:R tanks, or Immersive Engineering Jerrycans (or indeed vanilla buckets), because those items all do properly override those two methods.

Having said that, I should be able to reimplement the Heat Frame logic to not depend on the item having a container, but purely extract fluid via the fluid handler capability (which I do already - the dependency on the item being a container is historical and not really needed anymore)

**Comment by desht** [comment]
Fixed in 2.1.0 release
