### ISSUE TITLE
Collector drones are taking items from conveyor transport systems

### ISSUE THREAD

**Issue by yueh** [TeamPneumatic/pnc-repressurized#579]
### Minecraft Version
1.16.1

### Forge Version
32.0.108

### Mod Version
2.1.1-14

### Describe your problem, including steps to reproduce it
Collector drones and potentially anything with a pickup widget are collecting items from ImmersiveEngineering and Industrial Foregoing conveyors. Probably also similar transportation systems.

In case of IE it sets a boolean NBT tag named `PreventRemoteMovement` to allow other mods to ignore these. I have not seen something similar for IF.

**Comment by desht** [comment]
Agreed, drone item pickup should honour the `PreventRemoteMovement` tag.  IF should really be using the same tag since it's a bit of an informal standard, e.g. Botania also uses it for the Hopperhock and PNC already uses it for the chestplate magnet upgrade.

I might actually also add a checkbox to the Pickup Items widget gui to allow drones to ignore the tag (default behaviour would be to honour it) since there may be occasions where this is still desirable behaviour.

**Comment by desht** [comment]
Fixed in 2.2.0 and 1.4.5 release
