### ISSUE TITLE
Thermal Compressor sides show odd temperatures.

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#586]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.4.4-64

### Describe your problem, including steps to reproduce it
I'm having difficulty understanding the sides where the heat should be applied to. The picture shows north and south having high temps and east and west having low temps. The tool tip and manual says place hot and cold on opposite sides.

![2020-08-23_15 22 11](https://user-images.githubusercontent.com/4198031/90979331-aff05c00-e554-11ea-8ae0-898cdd715817.png)

This is with a block of packed/blue ice on the north and west sides.

![thermal-compressor](https://user-images.githubusercontent.com/4198031/90979247-29d41580-e554-11ea-92d5-e2b41a5bc2cb.png)

### Any other comments?
The scaling of the temperature meters is a bit strange, hard to see the temp difference when the scale changes. 

In the refinery controller the scale changes after 100 degrees, when the refinery starts to work, it would be nicer for the scale to change before the temp reaches the maximum, say at 90%.

**Comment by desht** [comment]
The Thermal Compressor is a little tricky to get right... I had to tread a very fine line between making it easily abusable for infinite free pressure and making it too weak to be useful.

What's happening here is that the heat from the campfire is vastly greater than the ice block's cooling.  There is a thermal connection between N/S and E/W sides, i.e. heat does leak across to equalize temperatures.  So the very hot campfire is basically overwhelming the ice block's cooling.  You still have a temperature differential of 11C, which will generate a little air.  

Another thing to try is heat sinks rather than ice blocks and see what you get then.  Also, try putting hot blocks on two sides (e.g. E/N sides, and heat sinks on the S/W sides).

One tip is that when you disable the machine via redstone, the thermal connection between opposite sides gets a *far* higher resistance, meaning heat crosses extremely slowly.  You can use this to turn this compressor into a sort of pressure "battery", storing energy in the form of a temperature differential.  When the pressure drops, turn the compressor on, and it will produce quite a bit of air/tick until the temperatures equalize again.  Turn it back off, and the differential will go back up quite fast.

**Comment by duncanwebb** [comment]
I see, there is a lot more heat flowing through the compressor than in previous versions. The gauges are not so useful in the machine, placing lava on one side, the heat differences looked small but in fact were high.

As you say in the manual it seems best suited to recover pressure from the hot or cold machines.

Thanks very much for the explanation.

**Comment by desht** [comment]
I'll take a look at the temp. gauges and see if they can be made more intuitive.

**Comment by duncanwebb** [comment]
The heat sink didn't work well with the camp fire. It worked well against a vortex tube that was heating a thermopneumatic processing plant.

Did you try a logarithmic scale on the gauges?

**Comment by desht** [comment]
Not using a log scale, no.  Not sure if that's useful.  What the thermal GUI scale should really do is scale based on the temperature difference rather than the actual temperatures.

Also spotted a bug: the gauges for the north/south sides are the wrong way round.  That one's trivial to fix, at least.

Also tested with a campfire, and the results are not great, no.  I had very good results with magma blocks, though, which aren't too hard to farm up in the nether.  They turn into netherrack when cooled, which is easier to break than obsidian.  Would be easy to automate with a drone.

But yeah... the Thermal Compressor isn't a great primary power source.  It's best used either for waste heat/cold reclamation, or as an energy store, using redstone to toggle between store and release.

**Comment by duncanwebb** [comment]
Are you sure that n/s are swapped round, the image would suggest that were correct? What I found difficult to grasp is the south side had a campfire and the north side had packed ice and the temperature difference was 10 deg C. The west side had blue ice and the east side had air and the temperature difference was 10 deg C. I would have expected the packed ice side to have a higher difference.

I tried a magma block and lava, the magma block converted to nether rack rapidly, the lava was very hot and generated a high-temperature difference and high pressure quickly.

I was thinking of using the thermal generator to power air grates in a mod farm but then realized that the air grates use a fair amount of pressure, so I ended up with a normal compressor which supplied enough pressure to move mods and drops to the slab channel. Adding a safety module in the generator was sufficient to prevent the pipes blowing up but the pressure rarely got that high.

Using the thermal generator to store waste heat is a great idea and I'm thinking about the ways to automate the off and on. I reckon that it will need to be controlled with a flow detector or pressure gauge.

**Comment by desht** [comment]
Build 68 (for 1.15) has some GUI tweaks which hopefully make it more intuitive.  Would be interested to hear your thoughts...

**Comment by duncanwebb** [comment]
Thanks, I'll check this new feature.

**Comment by duncanwebb** [comment]
Looks much better, cheers.
