### ISSUE TITLE
ATM6 Safety valve not working/changing with signal?

### ISSUE THREAD

**Issue by Aphex124** [TeamPneumatic/pnc-repressurized#623]
1.16.1
Forge-32.0.108
pneumaticcraft-repressurized-1.16.1-2.1.1-14

http://prntscr.com/unwlfe

Im new to the mod so this may be just my own error on doing something wrong.. Ive watched all the videos I could and everyone else's safety valve drops down .5 bar for every redstone signal applied, as well as lets the pressure out when it exceeds that limit.
All I've been able to accomplish is blowing my setup up every time I try.

**Comment by desht** [comment]
The videos you're watching are outdated, since a basic Safety Valve now just limits to 4.9 bar, which is enough to protect a low pressure network.

However, you have found a genuine bug, since the safety valve isn't releasing air at 4.9 bar when it should.  I'll fix this for the next release.

(In the meantime, you can put security upgrades in your compressors to prevent over-pressure situations, but also look at switching off compressors using pressure gauges and redstone to avoid wasting fuel...)

**Comment by desht** [comment]
Fixed in 2.2.3 release for 1.16.1
