### ISSUE TITLE
Dupe any item with /amadrone_deliver

### ISSUE THREAD

**Issue by phit** [TeamPneumatic/pnc-repressurized#642]
### Minecraft Version
1.16.3
### Forge Version
forge-34.1.25
### Mod Version
pneumaticcraft-repressurized-1.16.3-2.4.4-59

### Describe your problem, including steps to reproduce it
Put items you want to dupe in a chest , type `/amadron_deliver [who to deliver to] [coords of chest]`

the command can be run by not OP's allowing any player to duplicate any items since the command never removes any items from the chests.. 
https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.3/src/main/java/me/desht/pneumaticcraft/common/commands/ModCommands.java#L84

### Any other comments?
looks like this also applies to 1.15 and 1.14

please add a `requires(cs->cs.hasPermissionLevel(4))` to the command builder so this can only be run by OP's

**Comment by desht** [comment]
This has been at the back of my mind as something that's a bit too open, but yeah I need to lock it down since it's basically free items.  So thanks for reminding me.

Although permission level 2 should be fine, since level 2 allows use of the `/give` command anyway.

Will also do a backport for 1.15.2, but I don't care about 1.14 or earlier anymore.

**Comment by desht** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/commit/78b2c0a623653dedaf0705307110ff41b13c47f1

**Comment by desht** [comment]
Fixed in 2.4.5 (for MC 1.16.3)

**Comment by desht** [comment]
...and for 1.5.2 (MC 1.15.2)

**Comment by phit** [comment]
Thank you for the quick fix.
