### ISSUE TITLE
Drone "Right Click Block" with an empty bucket doesn't work

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#644]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.5.2-83

### Describe your problem, including steps to reproduce it
It does not seem that the right click block puzzle piece does not work with an empty bucket on a tank of thermopneumatic processing plant. It works when no item is given.

![image](https://user-images.githubusercontent.com/4198031/97449123-a529bd00-1931-11eb-827d-532a10ca8538.png)

### Any other comments?
The default mode is right click item, a bit odd for a right click block puzzle piece.

If you would like multiple issues for the following, just say. Some developers prefer separate tickets.
Is it possible to have an optional name for a location piece? It is sometime difficult to remember which location is which.
Is it possible for the TPP to emit a redstone signal when it has a valid recipe and space for the output? The refinery emits redstone when it has oil and space for output.
The memory only changes auto-collects mode when left-clicked on a vertical block, in the air of on the ground it does not change mode.

**Comment by desht** [comment]
I was able to make bucket clicking work as long as the mode is "Click Block", not "Click Item".  This might feel a bit counterintuitive, but it's unavoidable; the logic of filling a bucket when a modded tank is clicked is in the tank (the block), and not the bucket (the item).  Bearing in mind that vanilla buckets don't know anything about modded blocks that they can click.

> The default mode is right click item, a bit odd for a right click block puzzle piece.

That's historical; the "Right Click Block" piece should really these days just be called "Right Click".

> Is it possible to have an optional name for a location piece? It is sometime difficult to remember which location is which.

By "location piece", do you mean the Area widget?  I can see how that would be useful, but what I'd recommend instead is to set up a bunch of variables with meaningful names, and make your Area pieces use those rather than literal coordinates.  The Area widget doesn't render its variable name(s), but you can see them if you mouse over the widget.  I can take a look at having the widget render its coords or variable name, though.

> Is it possible for the TPP to emit a redstone signal when it has a valid recipe and space for the output? The refinery emits redstone when it has oil and space for output.

Probably, can you do a separate issue for that?  Although it would be via comparator (like the Refinery), not direct redstone output.

> The memory only changes auto-collects mode when left-clicked on a vertical block, in the air of on the ground it does not change mode.

I have a feeling I fixed that in 1.16 but didn't backport that fix to 1.15... however, it should work fine when clicking on the ground?  Not sure why that's not working for you...

**Comment by desht** [comment]
Here's an example program I stuck together to test the drone bucket right clicking, with labelling of Area widgets added.  Look good?

![image](https://user-images.githubusercontent.com/736831/97459078-46654300-1933-11eb-8ab5-589e7b47c896.png)

**Comment by desht** [comment]
Give build 84 a go and see what you think... three changes as described in the commit messages above.

**Comment by duncanwebb** [comment]
Oh I see, the right click item used the item specified to right-click the block defined by the area widget. And right click block right-clicks the block with whatever is in the inventory slot 1. 

If a drone had multiple inventory slots is slot filled with the first item or the last item, I think it is the first.

Very nice I like using variables to show the position of the area widget. (I did mean area widget).

The memory stick was doubling the click on the ground so it looked like it was not changing. However, it does not seem to be picking up the XP, the XP is being collected but the levels are not increasing.

Many thanks again, will give 84 a go now.

**Comment by desht** [comment]
> If a drone had multiple inventory slots is slot filled with the first item or the last item, I think it is the first.

Yep, the first.  Which is the item that renders as "held" by the drone.

> However, it does not seem to be picking up the XP, the XP is being collected but the levels are not increasing.

Yep build 84 should also fix the absorbed XP getting lost.

**Comment by duncanwebb** [comment]
Works fine and a nice solution for the labels.

**Comment by desht** [comment]
Gonna leave it open for now as a reminder to get this into both 1.15 and 1.16...

**Comment by desht** [comment]
Fixed in 1.5.3 release
