### ISSUE TITLE
Incompatibility with Immersive petroleum

### ISSUE THREAD

**Issue by ChiefLogan3010** [TeamPneumatic/pnc-repressurized#65]
Upon loading a world with both Pneumaticraft and IP in 1.12.2, the game freezes while building terrain due to what seems to be an incompatibility with Pneumaticraft and IP oil. Does not cause a crash but here's the log:
[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/1493332/latest.log)
The relevant information appears at around line 920 if that helps. If this is an IP bug then let me know and I'll report it to the developer.
Thanks!

**Comment by desht** [comment]
Hmm, this should have been fixed some time back.  Are you running the 0.1.0-47 build from CurseForge?

**Comment by desht** [comment]
```
22:59:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PneumaticCraft: Repressurized (pneumaticcraft)

Caused by: java.lang.IllegalStateException: Oil fluid does not have a block associated with it. The fluid is owned by immersivepetroleum. This could be fixed by creating the world with having this mod loaded after PneumaticCraft. This can be done by adding a injectedDependencies.json inside the config folder containing: [{"modId": "immersivepetroleum","deps": [{"type":"after","target":"pneumaticcraft"}]}]
```

The problem here is that IP registers "oil" as a fluid, but doesn't register a block for it (if I remember right, IP oil doesn't actually exist as pools in the world?).  But PNC:R does have oil pools as part of worldgen, and get really unhappy, as above, if it finds that oil has been registered as a fluid, without an associated block.

Try adding an ``injectedDependencies.json`` as suggested there; that should force PNC:R to load before IP, and register the oil block.  This should resolve the problem; if so, we can look at hardcoding a "before" dependency into PNC:R.  I think it's working for me here because PNC:R happens to be loading before IP in my dev instance - mod load order is pretty arbitrary and may depend on what other mods are in your instance.

**Comment by DeadSix27** [comment]
Another work-around would be renaming the jar to something like "A0-pressure... "
If that still works, I used to do that in 1.10, interestingly with Immersive Petroleum.
That used to make it load said mod first.

**Comment by Xiaminou** [comment]
It's not Immersive Petroleum, it's Buildcraft this time.

**Comment by Xiaminou** [comment]
It's not a different issue, I looked in his logs, he has buildcraft.

**Comment by DeadSix27** [comment]
@Xiaminou Oh, I thought you were the original author :P sorry, I thought he now has issues on 1.12 with BC.

**Comment by desht** [comment]
@Xiaminou do you have both Buildcraft and Immersive Petroleum installed?

I'll do some testing with Buildcraft installed and see what happens, but won't get a chance till tomorrow.  Does Buildcraft still add oil as a physical in-world block (I'm guessing it does) ?

**Comment by Xiaminou** [comment]
Yes I have both, my guess is that Buildcraft is taking priority for the Oil which means that Immersive Petroleum doesn't have Oil anymore and therefore the previous compatibility fix is no longer valid.

**Comment by desht** [comment]
I've done some more testing, with both IP & BC installed.
* If you add BC to an existing world (generated with PNC:R and IP installed) things will break right now.  It refuses to start with the "no block for oil" error.
* If you create a new world with PNC:R, IP and BC installed, it works OK.  PNC:R won't create oil (BC does that), diesel (IP does that) or lubricant (IP does that), but it *can* make and use those fluids in the refinery and thermopneumatic plant.  And BC oil (cool) does work in the refinery.  That works for me.

I'm also going to make a small change so that older worlds will load up if you disable PNC:R oil worldgen (because then oil doesn't need to exist as a block for PNC:R).  And I'm also adding that as a note in the startup error message, so you'll see something like this:
```
[09:18:37] [Server thread/ERROR] [pneumaticcraft]: Oil fluid does not have a block associated with it. The fluid is owned by [immersivepetroleum]. This might be fixable by creating the world with having this mod loaded after PneumaticCraft.
[09:18:37] [Server thread/ERROR] [pneumaticcraft]: This can be done by adding a injectedDependencies.json inside the config folder containing: [{"modId": "immersivepetroleum","deps": [{"type":"after","target":"pneumaticcraft"}]}]
[09:18:37] [Server thread/ERROR] [pneumaticcraft]: Alternatively, you can disable PneumaticCraft oil generation by setting 'D:oilGenerationChance=0.0' in the config file pneumaticcraft.cfg, and use the the oil from [immersivepetroleum].
```
followed by the IllegalStateException.  At that point editing ``pneumaticcraft.cfg`` and changing ``D:oilGenerationChance=0.0`` should let you get into your older world (although I make no guarantees about which versions of oil/diesel/lubricant will be available).

**Comment by desht** [comment]
FYI, build 69(+) on http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ contains the change I just mentioned.  If you'd like to try that out, I'd be interested to know if & how it helps.

**Comment by Xiaminou** [comment]
Well, except for the fact that Oil is now purple it worked fine.

**Comment by DeadSix27** [comment]
@Xiaminou That's BC, all their liquids are untextured currently.

**Comment by Xiaminou** [comment]
No they're not.
![2017-11-24_15 47 34](https://user-images.githubusercontent.com/8670392/33215116-e3e69f16-d12e-11e7-8539-8a33b81f36ae.png)

**Comment by desht** [comment]
@DeadSix27 you beat me to it :)  I'd noticed that in testing too.  Although I did also see some properly-textured BC oil geysers too.  In any case, I do not believe any broken textures are the fault of PNC:R at this point.

**Comment by desht** [comment]
@Xiaminou the oil in your screenshot is from IP, not BC.

**Comment by Xiaminou** [comment]
Oh I wasn't saying it's PNC:R's fault, just pointing it out.

**Comment by DeadSix27** [comment]
@Xiaminou In the world, place a bucket. That's where they are untextured, not in JEI.

**Comment by Xiaminou** [comment]
Oh okay.

**Comment by desht** [comment]
In any case, I think we are in good shape now regarding interop (and I didn't need to add a mod-specific dependency information; I'd much rather modpack authors controlled that via ``injectedDependencies.json``).  Just to recap, here's the strategy PNC:R uses:

* When fluids are registered (at preInit), PNC:R will check if a fluid of that name already exists.  If so, it'll use that in its recipes, but warn that it may not exist in block form.
* If the fluid doesn't exist already, PNC:R will register it, and also register a block for it (using the ``RegistryEvent.Register<Block>`` event, which happens between preInit and init).
* If at world load time, the "oil" fluid has no associated block, PNC:R will either 1) stop the world loading if its oil worldgen is enabled, or 2) just carry on if oil worldgen is disabled (``D:oilGenerationChance=0`` in pneumaticcraft.cfg).  In the case 1) it will also log messages about the user's options to resolve the problem.

The lack of block is only likely to be an issue if some mod loads before PNC:R and registers "oil" but does not register a block for it.  In that case, either disable PNC:R's oil worldgen and use the other mod's oil, or use ``injectedDependencies.json`` to ensure PNC:R loads first and gets a chance to register its oil block.

If all that makes sense, I will see if I can publish that somewhere that's easy to refer people to in case of future problems.

**Comment by MineMaarten** [comment]
As a side note to this, I'd like to add that, at the time I've extensively discussed with CPW about the best solution for handling this scenario, and this (simply logging the mod load instructions) was the best solution we could come up with. Not ideal, though.

**Comment by desht** [comment]
Closing this now, think we're as good as we can be on this one.
