### ISSUE TITLE
Just a question about P2P

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#658]
So, I remembered the old version of PneumaticCraft had an AE2 integration that added Pressure as a P2P capability. It was added in [this PR](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1769)

Is this still a thing in Repressurized by any chance?

**Comment by desht** [comment]
Sadly, no.  I did have some conversations with the AE2 team about this back in 1.12 and at the time there simply weren't the hooks in AE2 to allow for pressurized air to be passed over P2P.  However, I'll check back with them again now and see what the status is for 1.16...

It's definitely something I'd support if AE2 has the hooks for it.

Meantime, using a Requester Frame on a AE2 Interface does make the local logistics network available to AE2, so that support is still in...

**Comment by HipHopHuman** [comment]
Thanks for the prompt answer. I just had a memory from years ago, wanted to double-check it and then wondered if that feature carried over when you took over maintenance. Having Pressure in P2P would be a nice convenience factor, but it's not like it's a holy grail feature or anything :)

**Comment by TeamSpen210** [comment]
Since this [enum](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/api/java/appeng/api/config/TunnelType.java) is still present, it looks to be a hardcoded thing that'd have to be implemented on the AE side.

**Comment by desht** [comment]
Yeah, I think you're right.  Spoke to one of the AE guys yesterday, got the same impression. Maybe I need to PR it to AE2... one day perhaps.
