### ISSUE TITLE
[Question] How to add custom liquid fuels? 

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#673]
I've been trying to figure this out and struggling with it. I've got some fuels I'd like to add to the liquid compressor and I know in 1.12 this was possible with crafttweaker. However, we're using kubejs in 1.16 and I'm just not finding what I need for it to make sense. Is there data pack support for these? Or would I need to go about it differently?

**Comment by desht** [comment]
Hmm, it's probably not possible to do without Java code at the moment.  I'd like to get this working with kubejs though, so if I can figure out how to support it, I'll definitely get that in.

**Comment by MuteTiefling** [comment]
The simplest method is data packs. It'll inject them in the absence of more direct api support, and really covers most use cases.

**Comment by desht** [comment]
OK, build 88 turns all hard-coded fuel values into datapack recipes.  Take a look at https://github.com/TeamPneumatic/pnc-repressurized/tree/1.16.4/src/generated/resources/data/pneumaticcraft/recipes/pneumaticcraft_fuels/ for the default values.  All of the default recipes use fluid tags, but you can also use literal fluid names if you want (use `"fluid": "xxx"` instead of `"tag": "xxx"`).  Also the `"amount"` field is ignored, and you can omit it if you want.

**Comment by MuteTiefling** [comment]
Awesome stuff! I'll give this a peak tonight. Thanks so much :-D

**Comment by MuteTiefling** [comment]
Yep, Working perfectly, as usual :)

![image](https://user-images.githubusercontent.com/9543430/101438885-5af90b80-38e1-11eb-9ba2-9ef83ee3802e.png)


Also really love what you did with the GUI here to differentiate the fluids with identical tags.

**Comment by desht** [comment]
Fixed in 2.8.0 release
