### ISSUE TITLE
Stacked elevators not working correctly

### ISSUE THREAD

**Issue by clarence5192007** [TeamPneumatic/pnc-repressurized#681]
When i tried to stack elevators, the elevators dont work. When i tried to pressurize it, it aint pressurizing, even two stacks aint working pls help

1.16.3
Forge version: 34.1.41

Latest mod version

**Comment by desht** [comment]
Yeah the logic isn't right for lower elevators in the stack. Looking into it.

**Comment by desht** [comment]
Fixed in build 91 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/

Note that you will likely notice a pressure drop in your elevator stacks the first time after upgrading.  This is because each lower elevator (i.e. not the top of stack) also stores air normally now, adding 10000 volume (without Volume Upgrades) per elevator block to the system.  On the plus side, it means you have a larger volume by default, meaning smaller pressure drops when the elevator runs.

(Previously, lower elevators in the stack had some special handling to try and always use the top elevator's air handling, but that never worked properly, as you noticed).

Also increased the max elevator height to 6 blocks per stack height instead of 4, so you need fewer bases in a stack now for tall elevators.

**Comment by desht** [comment]
Fixed in 2.8.0 release
