### ISSUE TITLE
When the Program Controller mines itself it does not drop items in its inventory

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#686]
### Minecraft Version
1.16.4

### Forge Version
35.1.13

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.1-96

### Describe your problem, including steps to reproduce it
The program controller was maxed out with magnet, inventory and speed upgrades and had some tools. When the controller mined the area everything that was mined didn't drop when the controller was mined (including the drone).

### Any other comments?
The cause was a bug in the program.

**Comment by desht** [comment]
Not sure why inventory isn't being dropped: possible because it's trying to absorb items into itself, but "itself" has already left the world...

In any case, I think it might be better if the PC just ignored itself when running the Dig widget.  I can't think of a good reason for it to destroy itself...

**Comment by duncanwebb** [comment]
I fully agree, mining itself wouldn't have a purpose that I can think of.

**Comment by desht** [comment]
Fixed in 2.8.2 release
