### ISSUE TITLE
Compatibility issue with ultimate car mod

### ISSUE THREAD

**Issue by Thyloss** [TeamPneumatic/pnc-repressurized#705]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it

The pneumatic armor is unable to use it's own pressure for anything even with pressure available. it seems to detect it has pressure (boots up and can do anything that does not consume pressure) it will even let you try to use the functions that use pressure but they just won't do anything

to reproduce Install both pneumadticcraft and ultimate car mod 

### Any other comments?
I don't expect a fix as my guess is this is more the car mod causing the issue but seeing as how it messes up a core feature in this mod thought it should be known about

**Comment by desht** [comment]
I think the Ultimate Car mod is a red herring here - 2.9.0 should fix your problem.

There was a bug which caused armor feature enablement not to get sync'd to the server when armor was first put on (although logging in with the armor already on worked OK, which is why I didn't spot it for quite a while).  But 2.9.0 should fix your problem.

**Comment by Thyloss** [comment]
you were right I was testing for mod compatibility and part way though decided to just leave the armor on to speed testing up about the time I tested car mod lol
