### ISSUE TITLE
Dig Piece not respecting Black listed items

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#718]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
forge-1.16.4-35.1.36
### Mod Version
2.9.2-116
### Describe your problem, including steps to reproduce it

See below for sample program/screen shot.
The dig piece doesn't appear to respect blacklisted items. I thought it may be reserved to items set via the Item Assignment piece, but the filter via variable is properly being passed to all other pieces (you can remove the dig section/set the sign location in the sample program to test). Also, I used dirt/grass set within the filter, and the drone still digs those blocks.
This may be linked to #634 ? I should note that I am using the PC with a Network API.
Edit: Changed reference number of closed issue
![image](https://user-images.githubusercontent.com/14859369/104794602-b20ebd80-5776-11eb-8918-a987b854e219.png)

Pastebin to Prog ---> https://pastebin.com/76b6TXJD  You will have to adjust all cords

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Think I see the problem, and yes it is related to #634 but not quite the same problem.  I was doing an extra by-blockstate check with an empty item, to catch the case of blocks which don't drop anything (e.g. snow layers mined by drones without a shovel). The bug was that I should only be doing that when the currently-checked block has no drops, and I was doing it in all cases.

Next build will hopefully address that problem.  It behaves well with all the tests I've thrown at it so far, but would appreciate some extra testing before a 2.9.3 release, if you can... will update this when the build is pushed.

**Comment by desht** [comment]
Build 118 should fix this...

**Comment by Tekstack** [comment]
Thank you, and I'll test it out this build in a few hours.

**Comment by Tekstack** [comment]
The items set in the below screen shot are now being properly blacklisted on the dig piece except for the item set via Item Assignment piece (circled in red). The item variable is being handled correctly by all other pieces.

![image](https://user-images.githubusercontent.com/14859369/104821171-0c0b9380-5808-11eb-958c-7af2b068a167.png)

Edit: I am using Build 119

**Comment by desht** [comment]
I did find a bug where updates to the variable name in the Item Filter piece weren't getting synced to the server properly, so that'll be fixed in the next release.

Other than that, it appears to be working well.  This little program:
![prog1](https://user-images.githubusercontent.com/736831/104837628-ba1d4900-58ad-11eb-9fe8-bca4e09df870.png)
appears to work fine; it digs up everything except glass and dirt blocks in the given area.

If you're trying to match glass in a filter (either whitelist or blacklist), be sure to check "Match by Block" in the item filter, unless the drone has a silk touch tool equipped.

**Comment by desht** [comment]
Fixed in 2.9.3
