### ISSUE TITLE
Crash when scanning Enderman spawner with Block Tracker Uppgrade

### ISSUE THREAD

**Issue by ProfAggressor** [TeamPneumatic/pnc-repressurized#719]
[crash-2021-01-15_23.13.15-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5823844/crash-2021-01-15_23.13.15-client.txt)

### Minecraft Version
1.16.4

### Forge Version
35.1.36

### Mod Version
2.9.2-116

### Describe your problem, including steps to reproduce it
Problem: Scanning an Enderman spawner with Block Tracker upgrade in Pneumatic Helmet crashes client.

Reproduction:  Be near/look in the general direction of an Enderman spawner with active Block Tracker

### Any other comments?
If this happens to you, fixing it is as easy as turning the block tracker off while your armor is rebooting.  If you have speed upgrades installed and can't turn it off before the tracker is fully booted, God help you.

**Comment by desht** [comment]
Probably related to https://bugs.mojang.com/browse/MC-189565 - some entities are really really buggy in client-side vanilla spawners (you probably also have a bunch of log spam in your client log not related to PNC:R).  Note that other mobs may be affected too.

However, the block tracker shouldn't crash under these circumstances (my code was assuming the client-side spawner TE had a valid entity, when due to the above bug this is not always the case).  I'll add some extra validation in the block tracker code to account for this.

**Comment by desht** [comment]
Fixed in 2.9.3
