### ISSUE TITLE
[Feature Request] Program Controller suicide widget

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#734]
![image](https://user-images.githubusercontent.com/4198031/106615099-62006b00-656c-11eb-8418-b6db188852d1.png)

The suicide widget could cause the program to be ejected from the program controller. This would be handy for programs like Tek Stack's Greenhouse program. This program is really two programs in one, the first is to build the greenhouse and the second it to farm it. We could use redstone to control the running program, but the suicide piece would be a nice clean way to do this.

In the above image it would be ejected to the bottom is there is an inventory attached otherwise it would do nothing

**Comment by desht** [comment]
Yep, this is actually easy enough to do.  But I would drop the programmable item in-world if there isn't a suitable chest to receive it rather than do nothing.  Otherwise it'll just keep executing past the Suicide piece, effectively ignoring it.

(I might also make it so that programmed drone & network API's don't despawn when dropped in item form, to avoid losing valuable programs...)

**Comment by desht** [comment]
Added in 2.10.0 release
