### ISSUE TITLE
Pneumatic door bases only react to a strong redstone signals but not weak ones

### ISSUE THREAD

**Issue by ArsiTheFox** [TeamPneumatic/pnc-repressurized#744]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
1.16.5-forge-36.0.15

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.9.5-128

Not really a complete issue but probably a small tweak. Basically the Pneumatic door base only reacts to a strong redstone signal but not a weak one: 
![2021-02-17_04 45 06](https://user-images.githubusercontent.com/24835664/108193408-04772d00-70db-11eb-928b-18f109d59f48.png) <Weak Powered>
![2021-02-17_04 45 18](https://user-images.githubusercontent.com/24835664/108193420-080ab400-70db-11eb-94d5-86dbb1e61d88.png) <Strong Powered>

This makes it so you HAVE to send the signal into the main block and not the block next to it. Makes hiding redstone kinda annoying

Also an invert option would be nice so you can have a redstone signal already being sent having the door locked so no one can just place a lever and open the door

**Comment by desht** [comment]
I'll take a look at this, since a strong signal should work, you can work around it for now using 2 redstone modules on a pressure tube, and then camouflage the tube.  E.g.:

![2021-02-18_09 28 50](https://user-images.githubusercontent.com/736831/108336305-cc034c00-71cb-11eb-98ed-82e1ce325a23.png)

The facing module is in input mode, the other module (pointing at the door base to the left) is in output mode.  If you camouflage that tube, you can put a lever on it and it will pass the redstone signal to the elevator base.  You can also put the output redstone module in inverted mode if you want, so a signal is needed to close the door.

**Comment by desht** [comment]
Note that if you're really concerned about security, put the door base in "player nearby" or "player nearby and looking" mode, and hide a Security Station underneath.  Then *only* you (or anyone you add to the trusted list of the Security Station) will be able to open the door.

**Comment by desht** [comment]
Only the door cares about the redstone signal, not the door base.  In your picture, the lever on the door base works because it's providing a strong signal to the door through the door base.  I appreciate it would make sense for the door base to react too, but it's always been like this, and making the door base react would be a change in behaviour, potentially causing someone's existing build to break. 

I guess I could make this a GUI option in the door base, though (the default being the existing behaviour of not passing a signal along to the door).

However, you can still make this work: you can use redstone modules on camouflaged pressure tubes to run a redstone signal inside the surrounding wall, and point a redstone module in output mode at one of the doors.  Example:

![2021-02-18_10 10 34](https://user-images.githubusercontent.com/736831/108341509-9d886f80-71d1-11eb-857f-d8965cdafd30.png)

* The module on the far left (facing you) is in input mode.  If you camouflage that pressure tube, you can put a lever on it.
* The other module, pointing at the left door, is in output mode.
* There's pressure tube running all the way underneath the doors and bases - you would want to camouflage that too.  This carries both pressure for the elevator bases and the redstone signal between the two redstone modules.
* The other nice thing about this is that the output module can be set to inverted mode, getting you the inversion behaviour you want.

**Comment by desht** [comment]
Added in 2.10.1.  See new Pneumatic Door tab in the door base GUI, where you can enable passing the redstone signal along to the door.
