### ISSUE TITLE
[Feature Request] Add stack upgrades for PNC chamber interface

### ISSUE THREAD

**Issue by SinKane-MC** [TeamPneumatic/pnc-repressurized#751]
Description
It would be really nice (and maybe more server friendly?) to have the ability to upgrade the PNC chamber interfaces with stack upgrades to prevent the ping/pong of items trying to enter the chamber for crafting. For instance, if I need to make a lot of slime, or transistors/capacitors in a batch, I need to have a (large) chamber with numerous inputs, and the mats will bounce around trying to go into one of the input until successful or return to input storage.

Why would you like this added/changed?
It would be a QoL upgrade as well and potentially help with TPS not having to update all the entities as they move around aimlessly...

**Comment by BlueAgent** [comment]
You can put a whole stack of items in the interface already I think?
Do you mean an option for it to wait for a full stack of items before transferring?

I personally use a single input and a single output will full speed upgrades. The output is set to extract crafted items (default).

Also is this Minecraft 1.16.5? Because there shouldn't be a bunch of entities in that version.
It was changed to no longer use dropped items inside the chamber.

**Comment by desht** [comment]
There's no need for stack upgrades here. Just use a fast insertion system, e.g. Omnihopper with speed upgrades, high end mek pipes etc., and have some speed upgrades in your interface(s).

And no, items in the chamber aren't entities, and haven't been for a long time. They're just rendered with a TER.
