### ISSUE TITLE
dupelication bugs with curious and aerial interface

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#762]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.0.46
### Mod Version
2.10.3-149
### Describe your problem, including steps to reproduce it
duplication bug hard to explain, video probs explains better
### Any other comments?
https://www.youtube.com/watch?v=e5mEnNEWvpI&t=37s&ab_channel=47MarkIV

**Comment by desht** [comment]
Can you paste your `curios-server.toml` and any related datapack files here please, so I can set up an environment to reproduce this?

**Comment by desht** [comment]
Also, you're going to need to try to explain, because I don't see in that video where the dupe is happening (and if I pipe stuff in on my dev world, I don't see any duping).

**Comment by benbenlaw** [comment]
its just defualt curious server files

**Comment by benbenlaw** [comment]
Dupe Glitch

Need: Aerial Interface w/ 10 bar(Pneumaticraft) & a hopper

1. Set the face/side of the Aerial Interface to "curios"
2. Attach Hopper to that face/side
3. Insert items into hopper
4. Log out, log into
5. Profit

**Comment by desht** [comment]
Yeah I tried that, no dupe, no profit.

**Comment by benbenlaw** [comment]
hmm

**Comment by desht** [comment]
Well, I could never reproduce this, but I've decided to disable this feature (piping into & out of the curios slots) in the next release for two reasons:
1. Since there is the possibility of duping
2. Curios item handlers don't appear to prevent non-curio items from being inserted (looks like only slots prevent this, i.e. when inserting via the GUI)

Other Curios support (FE charging of items in curios slots and Memory Stick as a curio) won't be affected by this.

**Comment by desht** [comment]
"fixed" in 2.11.0 beta
