### ISSUE TITLE
Drone able to force teleport to players/crash server/I think corrupt player data but idk

### ISSUE THREAD

**Issue by thestormblazer** [TeamPneumatic/pnc-repressurized#775]
Attack drone thingy puzzle piece doesn't have a range which means on a small world 10k^2 for example it can be used for force teleporting to players that are loading chunks

Along with that if set to a large world and you attempt to do something like 1 million (couldn't be me ...) you will break the server and best guess it corrupts the player data of the person ridding the drone but I'm not sure about that part

Any ways if you added a range to the attack piece that would be neat it's one of the few that doesn't have one already (ps though keep it big enough so I can still use drones to guard my base xD)

**Comment by desht** [comment]
The attack piece already takes Area widgets, so it does have a range.  And the overall size of the Area widget is limited to 250,000 blocks by default (note: that's not a distance of 250,000 blocks - it's the total volume of the area, e.g. 50x100x50).  The limit can be changed in the config (`max_programming_area`) but it does use memory to store areas so don't raise it too much.

I need to see the program you used which caused the crash, and I still really need to see the crash log.  This problem *will not* be fixed without that information.

Separately, though, I could put a configurable limit on how far a drone is allowed to teleport because being able to port straight to players on a PvP server is abusable.  That would apply to *all* teleportation though, not just the attack piece.  That would have to be updated in config by the server admin, of course.

**Comment by desht** [comment]
Closed due to lack of response
