### ISSUE TITLE
[0.4.8] Lava Crystal from Blood Magic is consumed

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#781]
### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.1.0

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.11.3-168

### Describe your problem, including steps to reproduce it
If you use a bound lava crystal from Blood Magic in the Advanced Air Compressor from PNC, the crystal is consumed.
The Lava Crystal is a fuel source that should not be consumed, it takes life essence from one's Blood Magic soul network to work as furnace fuel.

### Any other comments?
Here's a link to the same issue but for The Betweenlands mod, thought it could be helpful: https://github.com/WayofTime/BloodMagic/issues/1623

**Comment by desht** [comment]
It's basically the same deal as Betweenlands - the compressor code shrinks the itemstack instead of replacing it with its container item.  However, the air compressors also explicitly prevent lava buckets from being used as fuel (that's what liquid compressors are for), which is why this problem hadn't been noticed before.

I think I'd be OK with lava crystals working though; this is basically a LP->pressure mechanic.  Should be a very easy change, I think.

**Comment by desht** [comment]
Fixed in build 174 if you feel like testing

**Comment by NielsPilgaard** [comment]
Sweet, thanks!
