### ISSUE TITLE
Pneumatic chestplate alone makes crash whilst loading configuration options

### ISSUE THREAD

**Issue by TheOnlyMann** [TeamPneumatic/pnc-repressurized#803]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
When equipping the pneumatic chestplate alone and pressing the U key, the game will crash. However, if you equip the boots first and press U, the menu shows up as normal. even with boots removed once again it shows normal.
This behavior resets on logging out of a sp world it seems.
### Any other comments?
[crash-2021-05-06_02.18.37-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6433697/crash-2021-05-06_02.18.37-client.txt)

https://user-images.githubusercontent.com/82017462/117282811-1ed1d300-aea0-11eb-8656-b5a06ddc2480.mp4

**Comment by desht** [comment]
Confirmed, it happens when you have no upgrades (with associated GUI screens) in any armor piece.  I think the best fix here is to always show the "Core Components" page regardless if which armor pieces are equipped and which upgrades are installed.  This also gives access to the armor coloring GUI, which might be useful.

**Comment by desht** [comment]
Fixed in 2.12.2
