### ISSUE TITLE
Possible bug with PNC Armor Upgrades

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#810]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/2238

### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.1.16

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.4-188

### Describe your problem, including steps to reproduce it

> dont know if it is a bug, but the armor upgrade of the armor set doesnt work right. it works on the chestplate and leggins, but only the toughness gets increased on the boots/helmet. Is it a bug or is it supposed to be this way?
> 
> ![2021-05-21_15 45 26](https://user-images.githubusercontent.com/42692808/119147157-9e88a180-ba4b-11eb-8fde-b4a99f4ad955.png)
> ![2021-05-21_15 44 49](https://user-images.githubusercontent.com/42692808/119147166-a0526500-ba4b-11eb-875b-151aa4006f71.png)
> ![2021-05-21_15 45 03](https://user-images.githubusercontent.com/42692808/119147171-a1839200-ba4b-11eb-8d06-58edfe8a20ce.png)
> 
> ![2021-05-21_15 45 13](https://user-images.githubusercontent.com/42692808/119147177-a21c2880-ba4b-11eb-8210-0518d4dab1d8.png)m.
> ![2021-05-21_15 45 17](https://user-images.githubusercontent.com/42692808/119147180-a34d5580-ba4b-11eb-9a83-4a33e6f90c8b.png)
> ![2021-05-21_15 45 23](https://user-images.githubusercontent.com/42692808/119147186-a47e8280-ba4b-11eb-8776-9c6d0bf15c77.png)

**Comment by desht** [comment]
Odd. I suspect it might be a display bug only, but I'll look into it. There's no special piece-specific handling for the armor upgrade...

**Comment by desht** [comment]
This is what I see with the helmet & 4 Armor Upgrades:

![image](https://user-images.githubusercontent.com/736831/119219812-49966b00-badf-11eb-8e01-9e70e577d769.png)

The "Armor" and "Armor Toughness" lines appear twice, but that's expected, since the armor upgrades add separate armor boost attribute modifiers for those two attributes.

Also did a bit of debugging on the server-side calculations and the armor upgrades in all pieces are definitely being accounted for when incoming damage reduction is calculated.

Not sure which mod converts the textual attribute displays to icons (Quark maybe?) but my guess it's not (always) detecting all the item attribute modifiers reliably on the client...?

**Comment by NielsPilgaard** [comment]
> Not sure which mod converts the textual attribute displays to icons (Quark maybe?) but my guess it's not (always) detecting all the item attribute modifiers reliably on the client...?

Me neither 😄 I'll try and figure it out. Thank you!
