### ISSUE TITLE
Server crash with 2.12.5-190

### ISSUE THREAD

**Issue by CloWnicide** [TeamPneumatic/pnc-repressurized#823]
### Minecraft Version: 
1.16.5

### Forge Version: 
36.1.18

### Mod Version: 
2.12.5-190

### Describe your problem, including steps to reproduce it: 
Upon installing the latest version available, my server crashes upon startup. The previous version I was using - 2.12.4-188 - works perfectly fine, but was causing another issue with generating a new world for singleplayer people using my modpack.

I would prefer to not have to keep 2 separate versions available for my modpack, so just need to know if this is something that has to be fixed on your end, or on Valkyrie of Nights end.

Log of crash: https://gist.github.com/CloWnicide/ec6ba41d6b2c38943138453288efd6eb

**Comment by desht** [comment]
It's actually quite difficult to determine who's really at fault here.  PNC:R uses recipes for its fuel values, to a) make it easy to modify via datapack/KubeJS etc. and b) easily sync them to the client for display in compressor GUIs.  The problem comes when other mods start querying item burn times on server load, before there's a world available (since recipe lookup really needs a world, due to the nature of the Minecraft's recipe system).  I've tried to kludge this before, but it turns out there are multiple corner cases.

Really not sure if PNC is at fault for using recipes for this functionality, or if Simple Generators is at fault for querying this sort of information far too early (i.e. before the world is loaded).  I can add another kludge for this in the short term to prevent the server crashing, but I'll keep this open and try to find a permanent clean solution.

**Comment by CloWnicide** [comment]
I see, I only remember having this issue previously and having to roll back 2 versions or so for my server to run. And it's either having Simple Gen or Pneumaticraft at this point, and I would rather have more tech than a simple power gen mod, but it's just unfortunate.

**Comment by desht** [comment]
Next release should fix it.  You can test the latest build if you like (see the #builds channel on discord).

**Comment by CloWnicide** [comment]
Works perfectly, any idea when it'll be uploaded to CurseForge so I can update my pack?

**Comment by desht** [comment]
Fairly soon I hope, got a couple of issues to deal with before a release.

**Comment by desht** [comment]
Fixed in 2.13.0
