### ISSUE TITLE
Feature Request: Energy Conversion Between Pneumaticcraft: Repressurized and Create

### ISSUE THREAD

**Issue by SwissxCore** [TeamPneumatic/pnc-repressurized#846]
Pneumaticcraft currently has a method of transferring energy between air pressure and forge energy, as most mods using energy use forge energy, Pneumaticcraft is able to interface with most mods to produce energy; Create, however, doesn't use forge energy, just as Pneumaticcraft doesn't, so I believe there is a need to be two new conversion blocks transferring the kinetic energy into air pressure, and vice versa.

The first, transferring kinetic energy produced by Create into compressed air, will be the **kinetic bellows**; as Create's energy is essentially free where Pneumaticcraft requires a source of fuel, the efficiency should be extremely low to compensate, but not low enough to warrant not using it at all; this will produce a constant source of compressed air as a very low rate, however, to use of a failsafe is recommended as it will keep pumping air regardless of the internal pressure.

And the second, transferring compressed air produced by Pneumaticcraft into kinetic energy, will be done using the **pneumatic quasiturbine**; as Create usually requires constant motion the efficiency here should opposingly be rather high, but once again, not high enough to prevent users from using Create's own devices.

These blocks will work as a means of users moving between Pneumaticcraft and Create without having to start from the very beginning in either.

**Comment by HipHopHuman** [comment]
This should go into an addon mod that bridges PNC with Create, IMO. The reason PNC supports RF/FE is because RF/FE is a standard that multiple mods use. It feels weird and incredibly niche to specifically add support to one other mod's energy system. Besides, you can already convert air pressure to rotation. Just use a Vortex Tube to heat a furnace, and then build a Create furnace engine around it.

![image](https://user-images.githubusercontent.com/70091260/125136467-29605100-e10b-11eb-92dd-f1f97e152c89.png)

**Comment by SwissxCore** [comment]
Converting air pressure to rotation using that method is incredibly clever, I would have never have thought about that, although it's a shame the energy doesn't transfer the other way.

I believe Pneumaticcraft requires additions if it wants to maintain relevance among the newer mods; it's a brilliant system, literally one of a kind, but is beginning to be outclassed in the new world.

Cheers.

**Comment by HipHopHuman** [comment]
> Converting air pressure to rotation using that method is incredibly clever, I would have never have thought about that, although it's a shame the energy doesn't transfer the other way.

It kinda does, use the hose pulley to pump from a source of LPG 10,000 blocks big (20x20x25). It'll consider the pool as an infinite source. Then use that in advanced liquid compressors. You can also use the Blaze Burner as a source of heat with the thermal compressor

> I believe Pneumaticcraft requires additions if it wants to maintain relevance among the newer mods; it's a brilliant system, literally one of a kind, but is beginning to be outclassed in the new world.

It has received many changes. Also look at this for anything on the roadmap: https://gist.github.com/desht/b604bd670f7f718bb4e6f20ff53893e2

**Comment by SwissxCore** [comment]
I see, then I apologise, my comment was uneducated and unwarranted. I would love to see any future roadmaps for future versions of the mod, I appreciate all of the effort that has been put into this mod so far and can't wait for the future.

**Comment by HipHopHuman** [comment]
I edited my previous comment to give you 2 options for converting rotation to pressure. As for future roadmaps, you could have a look at the suggestions in the github issues. They'll have an Enhancement: Feature tag.

**Comment by desht** [comment]
@HipHopHuman has already suggested a few clever options for converting between Create & PNC power systems.  In particular, a PNC-heated Furnace is very good for driving a furnace engine, a synergy I quite like.

I'm a lot less sanguine about generating pressure with Create, specfically because Create offers a couple of effectively infinite power sources very early on.  I'm aware you can do something similar with any solar cells or wind turbines that produce FE and a Flux Compressor, so any compressor which converts Create stress units would need to be a tier 2 heat-producing compressor, a bit like the Flux Compressor.

But if we're going that far, why not just use the Alternator from Create Crafts & Additions and hook it up to a Flux Compressor?

**Comment by desht** [comment]
@SwissxCore right now, the roadmap is pretty much anything that's been labelled as "Enhancement: feature" in the issues list :)  Some of those are things I do want to add, but simply can't right now due to time constraints...

I do need to sit down and figure out a more formal plan for future enhancements, though, and probably get that roadmap doc updated for new stuff.

**Comment by desht** [comment]
There's actually an addon mod called Compressed Creativity (for 1.16 and 1.18) which adds some Create/PNC power integration.  So closing this issue.
