### ISSUE TITLE
compressed tnt doesn't craft with explosion

### ISSUE THREAD

**Issue by mathieucrombe** [TeamPneumatic/pnc-repressurized#860]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

**Comment by desht** [comment]
Since explosion-crafting of compressed iron is literally the first thing anyone does with this mod, if this were a general problem then no one would be able to play the mod.  Therefore, this can be only be a modpack-specific problem, so I'd suggest talking to the modpack authors.  It's likely some other mod in the pack is interfering with the explosion crafting mechanic.

**Comment by desht** [comment]
I did a bit of testing with Chroma Tech 2, and I can confirm that the `ExplosionEvent.Detonate` event handler that PNC:R requires for compressed iron crafting isn't even getting fired in this pack.

So some other mod in the pack has broken Forge explosion events.  Definitely one for the pack author to investigate.

**Comment by North-West-Wind** [comment]
Hi! My modpack also has this issue and I've been testing with it. After a lot of testing, I found the mod that is causing it:
[Smooth Boot](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-forge)

https://github.com/UltimateBoomer/mc-smoothboot/issues/23
