### ISSUE TITLE
Harvesting drones not harvesting tomatoes

### ISSUE THREAD

**Issue by Kcitraa** [TeamPneumatic/pnc-repressurized#881]
### Mod Version Enigmatica 6 - 0.5.11

Harvesting drones is not harvesting farmer's delight tomatoes, it harvests other crops from the mods.

**Comment by desht** [comment]
Are tomatoes a right-click-to-harvest type of block (as opposed to break-to-harvest)?  Harvesters don't know about that kind of behaviour - they expect vanilla crop behaviour.

I will keep this open since there's the possibility of some integration here, but for now, you would need a programmed drone set to right-click the crop blocks.

**Comment by Kcitraa** [comment]
They are break to harvest, exactly the same as the lettuce and the lettuce are getting harvested. I programmed a drone to try to harvest the tomatoes and it won't do it.

**Comment by desht** [comment]
Really?  Because it looks to me like they're right-click to harvest: https://github.com/vectorwing/FarmersDelight/blob/1.16.5/src/main/java/vectorwing/farmersdelight/blocks/TomatoesBlock.java#L174-L179

`onBlockActivated()` is what's called when a block is right-clicked.

**Comment by Kcitraa** [comment]
Oh okay, sorry I misunderstood, I can harvest them by breaking them or by right clicking, I thought they were the same as lettuces. So I guess I need to program my drone to right click them instead. Thanks!
