### ISSUE TITLE
A promble of Thermopneumatic Processing Plant with use crafttweaker.

### ISSUE THREAD

**Issue by 854342681** [TeamPneumatic/pnc-repressurized#912]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.2.8
### Mod Version
2.14.4-258
### Describe your problem, including steps to reproduce it
I use follow code to create a recipe of Thermopneumatic Processing Plant,it can run without error when I reload crt. But no recipe be created in game, JEI also no recipe show even is blank.
I want to create a recipe with single item input ,and single fluid output.
`<recipetype:pneumaticcraft:thermo_plant>.addRecipe("test", <fluid:minecraft:empty>,<tag:items:forge:ores/iron> , <fluid:emendatusenigmatica:molten_iron> * 900, <item:minecraft:air>, 4.0, 1812,3023,2.0,false); `

**Comment by desht** [comment]
This will be fixed in the next release (but you can try a test build from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ if you want - build 274 or later).  Note that the recipe is actually getting created OK, JEI just didn't like the empty fluid ingredient because of a bug in my ingredient implementation.

Note also that your max temperature in the example recipe is a bit too high; the maximum useful temperature is 2273 (which is 2000C).

**Comment by 854342681** [comment]
Thanks for your help!

**Comment by desht** [comment]
Fixed in 2.14.6 release
