### ISSUE TITLE
Add a search bar in the Programmer GUI, to search for puzzle pieces

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#94]
As there's quite a list of puzzle pieces nowadays, this would be useful.

**Comment by desht** [comment]
We're a bit short of screen real-state in the Programmer GUI, but how about if the search bar appeared (and got keyboard focus) when the widget list is in expanded mode?  I would suggest putting the textfield just above the top left of the expanded widget view.  Typing anything in there would then filter the widgets in the expanded view to match the filter text.

A couple of questions, though:
* Should typing a Space insert the space character in the filter textfield, or toggle the widget view? My feeling here is have Space continue to toggle the view; I think it's unlikely whitespace will be needed in filter text.  The alternative could be to capture space character in the textfield (if it's focused), but add another hotkey for toggling the view (say, Tab?)
* When the widget view is in its default unexpanded mode, should the filter apply?  My feeling here is no, since the textfield won't be visible.

**Comment by desht** [comment]
Added in https://github.com/TeamPneumatic/pnc-repressurized/commit/4d0f5445eb5c694403e8c5738367786b60f46660
