### ISSUE TITLE
[Suggestion] Allow camo applicator to pull from danks/backpacks in inv

### ISSUE THREAD

**Issue by Rodg88** [TeamPneumatic/pnc-repressurized#942]
It would be great if the camo applicator could pul the needed blocks from storage items, like a dank or backpack for eg: https://www.curseforge.com/minecraft/mc-mods/dank-storage or https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
Personally I keep my building blocks in a dank, and currently I need to manually pull some out of the dank into my inventory in order to use the camo applicator. Building gadgets can currently do this, so should be possible somehow.

**Comment by HipHopHuman** [comment]
Neat idea. +1 from me

Would be nice if it supported Botania's Black Hole Talismans and Shulkerboxes as well.

**Comment by desht** [comment]
This actually turned out to be much easier than expected, since Dank Storage kindly exposes its inventory with a standard Forge item handler capability.  So yes, quick easy and useful feature will be in the upcoming 2.15.1 release.

I haven't tested Sophisticated Backpacks, but a quick peruse of the code suggests they'll probably work with this too (they also offer their inventory via the standard capability).

This doesn't include the Black Hole Talisman or the Shulker Box, sorry.  Both require custom interaction - I would like to support them, but probably not till 1.18 (I also need to do a rework of PNC's own inventory-in-item code before that...)

**Comment by desht** [comment]
Added in 2.15.1
