### ISSUE TITLE
[Request] Lootr support

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#953]
Just something that came up in enigmatica discord. The block tracker upgrade will locate vanilla chests, but not Lootr chests. Would be a nice compat to add since Lootr replaces all chests found in structures with their own.

**Comment by desht** [comment]
Hmm, Lootr explicitly disables capability-based inventory access for its blocks, presumably to disable mod-based access (pipes etc.).  It's this capability that the block tracker needs to identify inventories.

I'm not really overjoyed about adding specific compat for a mod that goes out of its way to disable standard access.  As a workaround though, you can add Lootr's chests to the `pneumaticcraft:block_tracker_misc_blocks` block tag, so they at least show up under the "misc blocks" category...

**Comment by MuteTiefling** [comment]
Ah right, I had forgotten that tag exists.

That'll work instead.

**Comment by desht** [comment]
I've figured out how to do this - 2.15.3 release will have support for finding Lootr chests, although the contents will not be displayed (mainly because I don't really want to start hooking into Lootr to force loot table generation via the block tracker update protocol).  But at least they'll show up in the tracker (with "Enable Inventories") as "Loot Chest".

**Comment by desht** [comment]
Added in 2.15.3 release

**Comment by MuteTiefling** [comment]
Nice! Thanks!
