### ISSUE TITLE
amadron tablet stealing emeralds bug report

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [TeamPneumatic/pnc-repressurized#958]
Version 1.16.5 36.2.9
### Mod Version
1.16.5-2.14.5-272
### Describe your problem, including steps to reproduce it
ordering 400 000mb of lubricate(with quantum tank and oak drawer) works fine but when ordering 500 000 or over, the drone just comes and picks up the emeralds, and never come back. see recording
launch up direwolf20 1.12.0 1.16(beta versions are bugged in ftb launcher btw) spawn in amadron tablet, oak drawer, emeralds, quantum tank. try order over 500 000mb of lubricate
### Any other comments?
https://youtu.be/wWzs6zGRmF4
dont mind my insanely fast autocrafting emeralds with botania, reliquary

**Comment by desht** [comment]
500,000mB of Lubricant is 2500 emeralds, which is just over 39 stacks.  That's too much for one amadrone (only has  a 36 stack capacity), so that offer's going to fail.

However this is a bug with PNC, since the Amadron tablet should prevent you from ordering that much.  I will add that as a check for the next release (2.15.3).

**Comment by desht** [comment]
Fixed in 2.15.3 release
